### ISSUE TITLE
I cannot create a BLK Namespaces

### ISSUE THREAD

**Issue by yassineba** [pmem/ndctl#10]
Hello,

I emulate a PMEM with 1G of RAM using a Virtual Machine with Fedora 25 Server, when I use ndctl tool, I can't create a BLK namespace with the following command : 
`$ndctl create-namespace --type=blk --mode=sector -e namespace0.0 -f`

I have non output result, and when I checking with : 

`$ndctl list`

I have the following output :  
`{
  "dev":"namespace0.0",
  "mode":"memory",
  "size":1073741824,
  "blockdev":"pmem0"
}
`

Thank you for your help.

**Comment by djbw** [comment]
This is expected. When you emulate PMEM the only region type available in your system is "pmem". You can see the full listing of available capacity in your system with:

     ndctl list -BRND

If you want to experiment with creating a BLK namespace you will need to use the unit test modules described in the README.
