### ISSUE TITLE
monitor exits silently if no DIMMs

### ISSUE THREAD

**Issue by kilobyte** [pmem/ndctl#102]
All I see in the syslog is:
```
Aug  1 03:33:47 valinor ndctl: ndctl monitor daemon started
```
yet the daemon is down.

RTFSing, I see that if there are no apparent DIMMs, the daemon will exit -- either with exit code 0 if `--daemon` is given or 250 if not (it tries to pass -ENXIO but exit codes have range 0..255).

I'd say that the daemon gracefully exiting due to nothing to monitor (be it because of no DIMMs , all DIMMs being broken, some kind of software error or misconfiguration, etc) is an interesting message for the admin.  Thus, could you please bump the *debug* message to *info* or *err*, and make it more explicit (like "No dimms to monitor, exiting.")?

**Comment by stellarhopper** [comment]
@kilobyte Thanks for the report - a "no dimms to monitor" message makes sense to me, I'll take a look at adding it for the next release.

**Comment by stellarhopper** [comment]
Fixed in v66
