### ISSUE TITLE
Add whitespace to /etc/dracut.conf.d/nvdimm-security.conf

### ISSUE THREAD

**Issue by johnwalicki** [pmem/ndctl#103]
The [dracut documentation](http://man7.org/linux/man-pages/man5/dracut.conf.5.html) for /etc/dracut.conf.d recommends that whitespace should surround a kernel module entry.
```
       add_drivers+=" <kernel modules> "
           Specify a space-separated list of kernel modules to add to the
           initramfs. The kernel modules have to be specified without the
           ".ko" suffix.
```

The ndctl (RHEL ndctl-64.1-2.el7.x86_64 rpm) package provides /etc/dracut.conf.d/nvdimm-security.conf
which does not have spaces surrounding it.

Why does this matter?  When dracut builds initramfs in the post install of a kernel upgrade it concatenates all of the modules specified in /etc/dracut.conf.d/ config files. When multiple /etc/dracut.conf.d/ config files don't have whitespace surrounding them, the system tries to load weird modules, aka  "nouveaulibnvdimm" and dracut throws an error.
       dracut: Failed to install module nouveaulibnvdimm

The fix is simple
```add_drivers+=" libnvdimm "```

**Comment by djbw** [comment]
@JeffMoyer this seems to be something local to the RHEL package? Upstream currently does not deploy a dracut configuration, although I would not  opposed to picking up that support.

**Comment by JeffMoyer** [comment]
Correct, this is a rhel-ism.  I'm not sure you would want to carry this in the ndctl upstream.  I've found that different releases have different requirements in this area.

**Comment by JeffMoyer** [comment]
@johnwalicki , I filed the following red hat bug to track this:
  https://bugzilla.redhat.com/show_bug.cgi?id=1740383
Dan, feel free to close this issue.

**Comment by djbw** [comment]
Cool, thanks Jeff!

**Comment by johnwalicki** [comment]
@JeffMoyer  Super - Thanks for opening the RH issue. We will track it with our TAM.
