### ISSUE TITLE
daxctl fails to reconfigure to system-ram when DAX modules built-in

### ISSUE THREAD

**Issue by stellarhopper** [pmem/ndctl#108]
From: Brice Goglin

$ daxctl reconfigure-device --mode=system-ram dax1.0 -v
libdaxctl: daxctl_insert_kmod_for_mode: dax1.0: a modalias lookup list was not created
error reconfiguring devices: No such device or address
reconfigured 0 devices

It looks like things were failing in kmod_module_new_from_lookup()

I changed my .config with this and now it works:
-CONFIG_DEV_DAX=y
-CONFIG_DEV_DAX_PMEM=y
-CONFIG_DEV_DAX_KMEM=y
+CONFIG_DEV_DAX=m
+CONFIG_DEV_DAX_PMEM=m
+CONFIG_DEV_DAX_KMEM=m

**Comment by stellarhopper** [comment]
Fix in `pending` and queued for v67

**Comment by Yitrus** [comment]
Hi, I had the same problem, but when I followed the way you provided and solved it, I encountered a new problem. So I would like to ask you about the Linux kernel version number and Linux version information that you used to solve this problem.

**Comment by stellarhopper** [comment]
@Yitrus This problem and solution has nothing to do with which version of Linux is being used. What exactly is the new problem you encountered?

**Comment by Yitrus** [comment]
@stellarhopper Thank you very much for your kind reply. I have solved the problem. It is a problem unrelated to ndctl. The reason is that I forgot to add "EXPORT_SYMBOL" to a function. I still have a lot to learn. Thank you again for your help.
