### ISSUE TITLE
`daxctl` command onlines memory as `ZONE_MOVABLE`

### ISSUE THREAD

**Issue by benbenolson** [pmem/ndctl#110]
Recently I have been using `daxctl` to online NUMA nodes of AEP memory (e.g. `daxctl reconfigure-device --mode system-ram dax0.0` or `daxctl online-memory dax0.0`). This particular system has 96GB of DRAM on NUMA node 1, and NUMA node 2 (the AEP) has about 768GB.

Upon running an application that used more than around 200GB of memory with `numactl --preferred=1 numactl --membind=1,2`, my friendly local OOM killer was killing my process. Checking `numastat -m` reveals that I still had somewhere around 600GB of AEP left on node 2, yet I couldn't seem to fault into that memory. Allocating specifically to it (`numactl --membind=2`) succeeded.

I finally found out that this is because `daxctl` is setting each memory region as `online_movable` ([this line](https://github.com/pmem/ndctl/blob/cec5975777e6a797432ce6117edc19674f4def83/daxctl/lib/libdaxctl.c#L1089)) when it onlines them. Per [this email](https://lwn.net/Articles/219589/), it seems as if the now-`ZONE_MOVABLE` node could only have around 96GB (the minimum size of my other NUMA nodes) faulted onto it. The OOM killer output and `numastat -m` made no indication of this, making this very confusing to debug.

Would it be possible to online memory as `ZONE_NORMAL` by default, but have a command-line option for `ZONE_MOVABLE` for users that specifically want that?

**Comment by stellarhopper** [comment]
@benbenolson You're right that we online the memory in ZONE_MOVABLE by default, and that right now it is just hardcoded in.

I'm working on an enhancement to detect other agents racing us to online memory, and point out such a situation. I can look into making the online behavior configurable as part of this.

I expect the normal use case for hotplugged memory will be to have it in ZONE_MOVABLE - I expect normally, you'd want to explicitly control access to this memory, and not want to have the kernel start using it for random things (which might cause general sluggishness, etc.). Therefore, I think it makes sense to default onlining as movable, but provide an option, say `--zone={movable|normal}` to override it.

For now, to work around this, you can reconfigure using the `--no-online` option, and you can set the `/sys/devices/system/memory/auto_online_blocks` attribute to `online`.  This will make the kernel automatically online new blocks into the normal zone, and the --no-online option will prevent daxctl from doing any onlining.

**Comment by benbenolson** [comment]
Thanks for the quick response-- I appreciate it. I've fixed the issue temporarily as you described.

In my experience, though, onlining an additional node of memory doesn't cause the kernel to allocate pages from it unless explicitly asked to; the new node stays completely unused until I `mbind` something to it.

Thus, at least from my perspective, `ZONE_MOVABLE` has the sole effect of disallowing NUMA spilling onto it-- which I think most users would want. If I fill up all of my DRAM, it's reasonable that I would want the kernel to begin allocating from AEP instead of OOMing.

In addition, I sunk quite a few hours into this subtle issue, not knowing that `daxctl` was marking the pages as `ZONE_MOVABLE` (whereas previously I was manually onlining the nodes, so didn't encounter this issue). I'd like to avoid others encountering this issue in the future, especially because the OOM killer's output makes no indication as to why the allocations failed, and `numastat` doesn't show that memory as inaccessible.

Is there some performance advantage to marking the memory as `ZONE_MOVABLE`?

**Comment by stellarhopper** [comment]
I've encountered the kernel happily allocating from the AEP node if it is in ZONE_NORMAL. I think @sscargal mentioned he has seen the same behavior as well.

The main motivation to leave it ZONE_MOVABLE by default is to avoid any unexpected sluggishness from kernel data structures, especially things like page tables ending up in this node.

Additionally, users may want to reconfigure back to a dax-device by hot-removing this memory, and ZONE_NORMAL precludes that.

The man page for reconfigure-device does call out:

```
      -N, --no-online
           By default, memory sections provided by system-ram devices will be brought online automatically and immediately with the online_movable policy. Use this option to disable the automatic onlining behavior.
```
But I agree that it can be made a bit more prominent.

Would it also help if the dax device listing also included an attribute displaying the current zone? Something like:
```
$ daxctl list
[
  {
    "chardev":"dax3.0",
    "size":16777216000,
    "target_node":3,
    "mode":"system-ram"
    "zone":"movable"
  }
]
```
And this would also be printed after a reconfigure operation.

**Comment by benbenolson** [comment]
Oh, all right. Perhaps it is better to leave it as `ZONE_MOVABLE`, then. 

I think it's good to make it a bit more prominent, as long as the change is easy to make. That would certainly have made things a bit more obvious.

Ultimately, though, I'm not sure that it's `daxctl`'s job to notify me about this subtlety. Since this is an allocation-time error, it should be the job of the kernel feature doing the allocating (or failing the allocation, as is the job of the OOM killer) to notify me of this issue. Perhaps `numastat` should be more clear about the distinction between `ZONE_NORMAL` and `ZONE_MOVABLE`, or the OOM killer's output in the logs could list the zones of the free memory on the nodes, indicating that it could onto fault to `ZONE_NORMAL` pages. As it is, the only way for me to realize my error was to `cat /sys/bus/node/devices/node2/memoryXXX/valid_zones`. That's outside of the scope of this Github issue, though.

Thanks for your time and attention.

**Comment by stellarhopper** [comment]
I'll actually reopen this since I'm working on a few changes related to this. I'll close it once resolved either way.

**Comment by benbenolson** [comment]
All right, sounds good! Let me know if you want me to do any additional testing.

**Comment by stellarhopper** [comment]
@benbenolson I posted some patches and CC'ed you on them to generally improve the onlining experience, and also add an option to online memory as 'normal'

I'd appreciate if you could try them out!

**Comment by benbenolson** [comment]
Sorry, I got busy going to a conference when this was posted.

I'll try them out now! Thanks!

**Comment by benbenolson** [comment]
Just tried it out with a few different configurations, offlining and onlining again. No issues, and (for people who might run into the same thing I did), this command does exactly what I want, where the AEP gets bound to the correct kernel driver and shows up in `ZONE_NORMAL`:

```
./daxctl/daxctl reconfigure-device --no-movable --mode=system-ram all
```

Thanks for your help! As far as I'm concerned, this is perfect.

**Comment by stellarhopper** [comment]
Thanks for testing it out Ben - closing this now, these changes are now in the v67 release.
