### ISSUE TITLE
daxctl-reconfigure-device misleading status information

### ISSUE THREAD

**Issue by michalbiesek** [pmem/ndctl#115]
## Description

Performing `daxctl reconfigure-device --mode=system-ram dax0.0 --force` on configuration described below results with misleading information that operation reconfigured 0 devices.
```

dax0.0: all memory sections (744) already online
reconfigured 0 devices
```

In fact daxctl device was **reconfigured to new mode** which confirm next `daxctl list` command.

## Configuration

**OS: Ubuntu 18.04.3 LTS
Kernel:  5.3.1
ndctl: version 66**

```
ndctl list
[
  {
    "dev":"namespace0.0",
    "mode":"devdax",
    "map":"mem",
    "size":4292870144,
    "uuid":"4a3c85a5-b50a-48f4-b9aa-6b55c684b873",
    "chardev":"dax0.0",
    "align":2097152
  }
]

daxctl list

[
  {
    "chardev":"dax0.0",
    "size":4292870144,
    "target_node":2,
    "mode":"devdax"
  }
]
```
## Details

IMHO the issue is related with return status of **dev_online_memory(dev)** - it returns in following place:
https://github.com/pmem/ndctl/blob/cec5975777e6a797432ce6117edc19674f4def83/daxctl/device.c#L177-L181

For details please see, [backtrace.txt](https://github.com/pmem/ndctl/files/3681667/backtrace.txt)

In the end the return status (**rc**) is equal 1 - and is not interpreted as new device, see:
https://github.com/pmem/ndctl/blob/cec5975777e6a797432ce6117edc19674f4def83/daxctl/device.c#L463-L464

**Comment by stellarhopper** [comment]
@michalbiesek Thanks - Yes I already have a fix for this in the patchset I'm working on - I'll add your Reported-by to it as well.

**Comment by stellarhopper** [comment]
Fixed in v67.
