### ISSUE TITLE
Update copyrights to 2020

### ISSUE THREAD

**Issue by sscargal** [pmem/ndctl#136]
In the recently released v68 we have old copyright dates that need to be updated to 2020:

```
# grep -Rs 2019 *
contrib/daxctl-qemu-hmat-setup:# Copyright(c) 2019 Intel Corporation. All rights reserved.
daxctl/device.c:/* Copyright(c) 2019 Intel Corporation. All rights reserved. */
daxctl/migrate.c:/* Copyright(c) 2019 Intel Corporation. All rights reserved. */
Documentation/copyright.txt:Copyright (c) 2016 - 2019, Intel Corporation. License GPLv2: GNU GPL
ndctl/load-keys.c:/* Copyright(c) 2019 Intel Corporation. All rights reserved. */
ndctl/util/keys.h:/* Copyright(c) 2019 Intel Corporation. All rights reserved. */
ndctl/lib/hyperv.c:/* Copyright(c) 2019, Microsoft Corporation. All rights reserved. */
ndctl/lib/hyperv.h:/* Copyright(c) 2019, Microsoft Corporation. All rights reserved. */
test/sub-section.sh:# Copyright(c) 2015-2019 Intel Corporation. All rights reserved.
test/daxctl-devices.sh:# Copyright(c) 2019 Intel Corporation. All rights reserved.
test/dm.sh:# Copyright(c) 2015-2019 Intel Corporation. All rights reserved.
util/iomem.h:/* Copyright(c) 2019 Intel Corporation. All rights reserved. */
util/iomem.c:/* Copyright(c) 2019 Intel Corporation. All rights reserved. */
```

**Comment by djbw** [comment]
Did you check to see which files were touched? Did you check to see which files had updates that warranted adjusting the copyright date? Did you consider sending a patch? I don't find this issue to be productive.

**Comment by sscargal** [comment]
I agree that not all the files listed have changed in v68, so they should be excluded from further changes. 

What initiated this issue was the modified man pages and online HTML versions available through https://pmem.io/ndctl/.  `Documentation/copyright.txt` is used in the footer for the man pages, of which several were updated for v68. For this scenario, looking at the dates of the files containing 2019 is not necessarily the correct approach since we're including them in other files that have been modified. See #https://github.com/pmem/ndctl/commit/b77ca0221d2ecd7b55d509c4c9f50aaba28f3aa1


The issue affects documentation/man pages in the master branch and the gh-pages branch.
