### ISSUE TITLE
Compiling ndctl failed in Debian10 OS when ./configure

### ISSUE THREAD

**Issue by bambooHaw** [pmem/ndctl#142]
./configure: line 10128: syntax error near unexpected token `KMOD,'
./configure: line 10128: `PKG_CHECK_MODULES(KMOD, libkmod)'

**Comment by stellarhopper** [comment]
@bambooHaw What distro/environment is this in? Do you have the relevant kmod/libkmod packages installed, especially their 'dev' or 'devel' variants?

**Comment by bambooHaw** [comment]
Sure. I have installed libkmod-dev/kmod packages, and the version are all 26-1. 
libkmod-dev is already the newest version (26-1).
kmod is already the newest version (26-1).


And when I first execute the autogen.sh in ndctl/ directory, there's always an error(but success with trying again), error msg is at below,
configure.ac:40: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1


BTW. I have installed all packages noted with "BuildRequires:" lines in ndctl.spec.in.
https://github.com/pmem/ndctl/blob/master/ndctl.spec.in

I'm so sad now.

**Comment by bambooHaw** [comment]
Does that mean tool-ndctl not being supported on Debian10? 
Or I need a special m4 configuration?

Somebody, please help me fix this issue.
Thank you in advance.

**Comment by kilobyte** [comment]
It works for me, including [official Debian repos](https://tracker.debian.org/pkg/ndctl) for unstable and buster-backports.

If you're after unmodified ndctl, I'd recommend turning on buster-backports in your apt sources.  Otherwise, if you want to build ndctl yourself, the list of dependencies is [here](https://github.com/kilobyte/ndctl/blob/debian/debian/control).

**Comment by bambooHaw** [comment]
Too many things to make time fly. 
Thank you very much @kilobyte . 
I'll try your solutions today.

**Comment by bambooHaw** [comment]
Although I want to build ndctl by myself, it also works for me using `apt install ndctl && apt install libndctl-dev` for me in DebianOS10. So I use ndctl from buster now.

Thank you very very much. @stellarhopper  @kilobyte

**Comment by bambooHaw** [comment]
using `apt install ndctl && apt install libndctl-dev` directly from buster.
