### ISSUE TITLE
Unable to compile ndctl on wsl

### ISSUE THREAD

**Issue by janandra-blue** [pmem/ndctl#148]
Env : DEBIAN FOR WSL
Packages Installed :  debian build essential package, git, autoconf, pkg-config, libtool, asciidoctor.

Steps to Reproduce:
1) clone repo , ndctl version on which issue reproduced v69
2) run ./autogen.sh
3) run ./configure CFLAGS='-g -O2' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64

Error : 

checking pkg-config is at least version 0.9.0... yes
checking for KMOD... no
configure: error: Package requirements (libkmod) were not met:

No package 'libkmod' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables KMOD_CFLAGS
and KMOD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

But,
kmod exists , when run apt-install kmod , the output is as follows

Reading package lists... Done
Building dependency tree
Reading state information... Done
kmod is already the newest version (26-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by janandra-blue** [comment]
This was resolved after running 
apt-get install -y git gcc g++ autoconf automake asciidoc asciidoctor bash-completion xmlto libtool pkg-config libglib2.0-0 libglib2.0-dev doxygen graphviz pandoc libncurses5 libkmod2 libkmod-dev libudev-dev uuid-dev libjson-c-dev libkeyutils-dev

Ref : https://docs.pmem.io/persistent-memory/getting-started-guide/installing-ndctl

**Comment by seghcder** [comment]
Apologies for adding to a closed ticket - I'm curious as to whether you've been able to get pmem emulation (ie via memmap grub option) working on WSL2?
