### ISSUE TITLE
Make fails on Ubuntu

### ISSUE THREAD

**Issue by Nighthawk75** [pmem/ndctl#15]
I believe I have all of the required libraries and packages installed. 

Autogen and Configure steps run smoothly, but when I ran make, there is an error relating to the uuid.   I am not too familiar with this and could use some guidance. 

root@NVDIMM:~# git clone https://github.com/pmem/ndctl.git
Cloning into 'ndctl'...
remote: Counting objects: 2546, done.
remote: Total 2546 (delta 0), reused 0 (delta 0), pack-reused 2546
Receiving objects: 100% (2546/2546), 722.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1751/1751), done.
Checking connectivity... done.
root@NVDIMM:~# cd ndctl/
root@NVDIMM:~/ndctl# ls
autogen.sh  ccan          contrib  daxctl         git-version      licenses  Makefile.am     make-git-snapshot.sh  ndctl.spec.in  README.md    sles  test.h
builtin.h   configure.ac  COPYING  Documentation  git-version-gen  m4        Makefile.am.in  ndctl                 nfit.h         rpmbuild.sh  test  util
root@NVDIMM:~/ndctl# uname -a
Linux NVDIMM 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@NVDIMM:~/ndctl# ./autogen.sh
Activated pre-commit hook.
GIT_VERSION = 56
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:22: installing 'build-aux/compile'
configure.ac:27: installing 'build-aux/config.guess'
configure.ac:27: installing 'build-aux/config.sub'
configure.ac:10: installing 'build-aux/install-sh'
configure.ac:10: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'

----------------------------------------------------------------
Initialized build system. For a common configuration please run:
----------------------------------------------------------------

./configure CFLAGS='-g -O0' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib

root@NVDIMM:~/ndctl# ./configure CFLAGS='-g -O0' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for a sed that does not truncate output... (cached) /bin/sed
checking for asciidoc... /usr/bin/asciidoc
checking for xmlto... /usr/bin/xmlto
checking for typeof syntax and keyword spelling... typeof
checking whether byte ordering is bigendian... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for KMOD... yes
checking for UDEV... yes
checking for UUID... yes
checking for JSON... yes
checking for BASH_COMPLETION... yes
checking for ARS support... yes
checking for CLEAR ERR support... yes
checking for device DAX support... yes
checking for SMART support... yes
checking for linux/version.h... yes
checking for __secure_getenv... no
checking for secure_getenv... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating daxctl/lib/Makefile
config.status: creating ndctl/lib/Makefile
config.status: creating ndctl/Makefile
config.status: creating daxctl/Makefile
config.status: creating test/Makefile
config.status: creating Documentation/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing gen-libndctl.h commands

        ndctl 56
        =====

        prefix:                 /usr
        sysconfdir:             /etc
        libdir:                 /usr/lib
        includedir:             ${prefix}/include

        compiler:               gcc
        cflags:                 -g -O0
        ldflags:

        logging:                yes
        debug:                  no

root@NVDIMM:~/ndctl# make
  GEN      version.m4
make --no-print-directory all-recursive
  GEN      version.m4
Making all in .
  GEN      version.m4
  CC       ccan/str/str.o
  CC       ccan/str/debug.o
  CC       ccan/list/list.o
  AR       libccan.a
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       util/parse-options.o
  CC       util/usage.o
  CC       util/size.o
  CC       util/main.o
  CC       util/help.o
  CC       util/strbuf.o
  CC       util/wrapper.o
  CC       util/filter.o
  AR       libutil.a
ar: `u' modifier ignored since `D' is the default (see `U')
  GEN      rhel/ndctl.spec
  GEN      sles/ndctl.spec
Making all in daxctl/lib
  CC       ../../util/sysfs.lo
  CC       ../../util/log.lo
  CC       libdaxctl.lo
  CCLD     libdaxctl.la
  GEN      libdaxctl.pc
Making all in ndctl/lib
make --no-print-directory all-am
  CC       libndctl.lo
  CC       libndctl-ars.lo
  CC       libndctl-smart.lo
  CC       libndctl-hpe1.lo
  CCLD     libndctl.la
  GEN      libndctl.pc
Making all in ndctl
  CC       ndctl.o
  CC       builtin-create-nfit.o
  CC       builtin-xaction-namespace.o
  CC       builtin-xable-region.o
  CC       builtin-dimm.o
  CC       ../util/log.o
  CC       builtin-list.o
  CC       builtin-test.o
  CC       ../util/json.o
  CC       util/json-smart.o
  CCLD     ndctl
Making all in daxctl
  CC       daxctl.o
  CC       list.o
  CC       ../util/json.o
  CCLD     daxctl
/usr/bin/ld: ../util/json.o: undefined reference to symbol 'uuid_unparse@@UUID_1.0'
//lib/x86_64-linux-gnu/libuuid.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:458: recipe for target 'daxctl' failed
make[2]: *** [daxctl] Error 1
Makefile:736: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:523: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by djbw** [comment]
Give the pending branch a try. It has the following fix:

22bffbecb16d daxctl: add libuuid to the build

**Comment by djbw** [comment]
Fixed in v57
