### ISSUE TITLE
Adding a 'NAME' attribute to an existing namespace adds 'NAME' to the wrong namespace and destroys the selected namespace

### ISSUE THREAD

**Issue by sscargal** [pmem/ndctl#152]
Problem Statement:

When reconfiguring a namespace to add a 'name' attribute, ndctl adds the name attribute and value to the wrong namespace and destroys the selected namespace.

Config:

- Fedora 33
- Kernel 5.8.16-300.fc33.x86_64
- ndctl 70.4.gfaa39a6 (built from source)

Issue:

```
// Create 12 namespaces of ~1GB each 
# for i in {0..11}; do  ndctl create-namespace --size 1006632960 --region 0; done
```

If I add a name to the newly created namespaces, ndctl adds the 'name = <value>' to a seemingly random namespace and disables the selected namespace

```
# ndctl create-namespace --name pmem01 --force --reconfig namespace0.1
{
  "dev":"namespace0.11", <-- This isn't the namespace I entered in the command!!!
  "mode":"fsdax",
  "map":"dev",
  "size":"944.00 MiB (989.86 MB)",
  "uuid":"982dfe23-0f0d-4289-a552-c675c48ceeb6",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem0.11",
  "name":"pmem01"
}
```

However, `namespace0.1` is now in a NULL'd/disabled state:

```
# ndctl list -iN --namespace namespace0.1
[
  {
    "dev":"namespace0.1",
    "mode":"raw",
    "size":0,
    "uuid":"00000000-0000-0000-0000-000000000000",
    "sector_size":512,
    "state":"disabled"
  }
]
```

Continuing the command for different namespaces continues to show this odd behavior

```
# ndctl create-namespace --name pmem02 --force --reconfig namespace0.2
{
  "dev":"namespace0.1",  <-- Wrong namespace!
  "mode":"fsdax",
  "map":"dev",
  "size":"944.00 MiB (989.86 MB)",
  "uuid":"ef2d8c17-99cc-4a62-9785-40317340d220",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem0.1",
  "name":"pmem02"
}

# ndctl create-namespace --name pmem03 --force --reconfig namespace0.3
{
  "dev":"namespace0.2",
  "mode":"fsdax",
  "map":"dev",
  "size":"944.00 MiB (989.86 MB)",
  "uuid":"a88c91b0-a436-47f8-b0ec-43891eb8aa43",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem0.2",
  "name":"pmem03"
}
[...snip...]
```

The `ndctl-create-namespace` man page says the original attributes, with the exception of `uuid`, should be copied across to the new namespace. The above demonstrates the selected namespace is getting destroyed, but not recreated.

```
       -e, --reconfig=
           Reconfigure an existing namespace. This option is a shortcut for the following sequence:
           •   Read all parameters from @victim_namespace
           •   Destroy @victim_namespace
           •   Create @new_namespace merging old parameters with new ones :: Note that the major implication of a destroy-create cycle is that data from
               @victim_namespace is not preserved in @new_namespace. The attributes transferred from @victim_namespace are the geometry, mode, and name (not uuid
               without --uuid=). No attempt is made to preserve the data and any old data that is visible in @new_namespace is by coincidence not convention. "Backup
               and restore" is the only reliable method to populate @new_namespace with data from @victim_namespace.
```

**Comment by djbw** [comment]
This is indeed surprising, and while it is by design there might be ways to reduce its occurrence. This is an artifact of the destrory/create cycle to reconfigure a namespace the internal sequence goes:

1/ Read all configuration from 'victim'
2/ Destroy 'victim' (kernel may reap the namepsace device name at this point)
3/ Pick default namespace to create (this is usually the next 'seed' device that is n+1 from the previous creation attempt)

One way to fix this may be to not destroy the existing kernel-device. Writing zero to the namespaceX.Y/size property arranges for the namespace device to be deleted as long as it is not namespaceX.0, instead the 'destroy' step could just be a size change without reducing the 'size' to zero.

**Comment by sscargal** [comment]
Thanks for the info. Would it be possible to add or edit namespace attributes without reconfiguring the entire namespace, perhaps through a new `ndctl set` command?

**Comment by djbw** [comment]
> Thanks for the info. Would it be possible to add or edit namespace attributes without reconfiguring the entire namespace, perhaps through a new `ndctl set` command?

That's what reconfigure-namespace does... it only incorporates the changed settings, it's just the kernel device disassociation that is jarring.

**Comment by stellarhopper** [comment]
@sscargal v71 has @djbw 's fix for this - did you get a chance to test that out? Feel free to close this if this is fixed. Thanks!

**Comment by sscargal** [comment]
@stellarhopper @djbw The fix looks good, thank you!

Config:

- Fedora 33
- Kernel 5.8.16-300.fc33.x86_64
- ndctl 71.2.gea014c0 (built from source)

```
// Create 12 namespaces of ~1GB each 
# for i in {0..11}; do  ndctl create-namespace --size 1006632960 --region 0; done
```

Add/change the name of a namespace now works as expected

```
# ndctl create-namespace --name pmem01 --force --reconfig namespace0.1
{
  "dev":"namespace0.1",
  "mode":"fsdax",
  "map":"dev",
  "size":"944.00 MiB (989.86 MB)",
  "uuid":"8d126f55-9959-40a8-8493-6203cec1c948",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem0.1",
  "name":"pmem01"
}

# ndctl create-namespace --name pmem01-new --force --reconfig namespace0.1
{
  "dev":"namespace0.1",
  "mode":"fsdax",
  "map":"dev",
  "size":"944.00 MiB (989.86 MB)",
  "uuid":"886d37b0-bbf3-41f4-82e8-7676bf5f4f1d",
  "sector_size":512,
  "align":2097152,
  "blockdev":"pmem0.1",
  "name":"pmem01-new"
}
```

Closing issue as resolved.
