### ISSUE TITLE
The "persistence_domain" is unknown

### ISSUE THREAD

**Issue by lizhenxin-github** [pmem/ndctl#154]
issues:

`sudo ndctl list -Ri`

```
{
    "dev":"region4",
    "size":270582939648,
    "available_size":270582939648,
    "type":"pmem",
    "numa_node":0,
    "iset_id":5206423646373291076,
    "state":"disabled",
    "persistence_domain":"unknown"
}
```
In addition, I destroyed all namespaces and disabled all regions but they became activated when I rebooted my system.

**Comment by djbw** [comment]
Does your BIOS publish the ACPI NFIT Platform Capabilities structure?

Disabling a namespace or a region is only temporary until the next autoprobe event which is either reboot or reload the nfit.ko module.

**Comment by lizhenxin-github** [comment]
Thanks. This issue is solved by replacing the system kernel and publishing the ACPI NFIT.
