### ISSUE TITLE
ndctl 70: retry on ndctl update-firmware fails after initial ARS collision

### ISSUE THREAD

**Issue by Mark-Baker** [pmem/ndctl#155]
Environment:
ndctl 70
kernel 4.14.35-2046.el7uek.x86_64

Use case:
Updating firmware with ndctl, config is AppDirectNotInterleaved Instead of waiting for ARS to complete, update firmware is run oneach DIMM, possible failure due to a collision with ARS running on that DIMM is anticipated, with recovery from this failure being to sleep 30 sends and retry, up to 10 times. Apparently with ndctl70, when there is a collision, after ARS is complete, that DIMM always indicates it is busy with a firmware update.

Attached is a repro script that does the following
for all DIMMs
    ndctl load firmware DIMM
    if failure
        break

if failure
    wait for the entire ARS to complete    // simplify the test case
    ndctl load firmware failed DIMM

---- repro script ndctl_fw.sh , run when initial ARS on boot is running, or start-scrub
#!/bin/bash
FW=/boot/efi/BKC/ww43/FW_2.2.0.1529/fw_bwva1_2.2.0.1529_rel.bin

NDCTL_VERS=$(ndctl version)
load_fw(){
    if (( $NDCTL_VERS == 69 ))
        then    
            ndctl update-firmware ${1} -f ${FW} 
        else if (( $NDCTL_VERS == 70 ))
        then    
            ndctl update-firmware ${1} -f ${FW} --force
        else    
            echo "ndctl version ?" $NDCTL_VERS 
            exit -1     
        fi      
        return $?
    fi  
}

failed=
for nmem  in $(ndctl  list -D | jq  -r '.[] | .dev' )
do
    load_fw $nmem
    if (( $? ))
    then
        echo $nmem failed
        failed=$nmem
        break   
    fi  
done

if [ $failed ]
then
    echo waiting for ARS to complete
    ndctl wait-scrub
    load_fw $failed
fi

**Comment by djbw** [comment]
@Mark-Baker would it be possible to test this on a recent kernel? My concern is that the ARS engine on that kernel might be restarting ARS rather than letting the BIOS cancel ARS in response to the incoming firwmare-update. The other option to make sure that ARS does not collide with firmware-update is to prevent the kernel from launching it in the first instance by adding "nfit.no_init_ars" to the kernel command line...

However, that option and the current version of the ARS state machine arrived in the v4.17 kernel, so again I'm not sure if the uek kernel baseline has that incorporated.

**Comment by Mark-Baker** [comment]
@djbw This issue reproduces with a 4.17 kernel. 

[root@ban25uut133 mb]# uname -r
5.4.17-2036.100.6.1.el7uek.x86_64

[mb]# ./ndctl_fw.sh 
{
  "dev":"nmem15",
  "id":"8089-a2-1950-00001b1d",
  "handle":"0x1311",
  "phys_id":"0x62",
  "security":"disabled",
  "firmware":{
    "current_version":"0x202001529",
    "can_update":true,
    "next_version":"0x202001529",
    "need_powercycle":true
  }
}
updated 1 nmem.
  Error: update firmware: nmem1: device busy with other operation (ARS?)
  Error: update firmware: nmem1: unhandled error 14
updated 0 nmem.
nmem1 failed
waiting on 0x0011
---DimmID=0x0011---
   ARSStatus=Completed
  Error: update firmware: nmem1: busy with another firmware update
updated 0 nmem.

Can you clarify your comment " BIOS cancel ARS in response to the incoming firwmare-update"? It was my understanding that the -force option did not cause cancellation of ARS when firmware update is attempted, but to bypass the exit if ARS is running. Seen below in ndctl/dimm.c

  if (ndctl_bus_get_scrub_state(bus) > 0 && !param.force) {
                err("%s: scrub active, retry after 'ndctl wait-scrub'",
                                devname);
                return -EBUSY;
        }

As for the suggestion to disable ARS on boot via nfit.no_init_ars, this was my first suggestion to the user. This is not practical for them, as the update firmware is infrequent, and they don't want to disable ARS on every boot and have to start elsewhere, nor do they want to have a custom grub entry for the update firmware case.

**Comment by Mark-Baker** [comment]
In the failure case, my guess is that the following is happening

ND_INTEL_FW_START_UPDATE is set, 
ndctl attempts to load FW, the operation fails because ARS is running on that DIMM
the update-firmware fails, but the FW_START_UPDATE bit is not cleared

On the next invocation of ndctl update-firmware, after  ARS is complete on the given DIMM, 
ND_INTEL_FW_START_UPDATE is still set, and the operation fails. 
       
        status = ndctl_cmd_fw_xlat_firmware_status(cmd);
        if (status == FW_EBUSY) {
                err("%s: busy with another firmware update", devname);
                return -EBUSY;
        }

It takes a reboot to clear this condition

**Comment by djbw** [comment]
@Mark-Baker can you give the issues/155 branch a try to see if resolves the issue?

**Comment by djbw** [comment]
Wait, I need to retry the submit after the abort... hold-on...

**Comment by djbw** [comment]
Ok, I refreshed the branch, ready for you to give it a try.

**Comment by jchu314atgithub** [comment]
Hi, Dan, 

Mark tested the above patch and found the firmware abort fails.   I added below

https://lists.01.org/hyperkitty/list/linux-nvdimm@lists.01.org/thread/WCFPCMTQLZIRLGUC3EFGRMEJMWI7GBQI/

and the test passed.

Our product manager is asking whether it's possible to respin ndctl v71, to like v71.1, to include both patches ?  Thank!

**Comment by djbw** [comment]
@jchu314atgithub much appreciated! I owe you one.

@stellarhopper might you be able to cut a v71.1? I'll send out the firmware fix on the list.

**Comment by jchu314atgithub** [comment]
Thank you so much Dan!

**Comment by stellarhopper** [comment]
Yep I can cut a 71.1 release tomorrow.

**Comment by stellarhopper** [comment]
v71.1 is out now, closing this.
