### ISSUE TITLE
Init-label fails in vSphere VM

### ISSUE THREAD

**Issue by Tianyang-Zhang** [pmem/ndctl#156]
I was following `ndctl` user guide(https://docs.pmem.io/ndctl-user-guide/managing-label-storage-areas-lsa#initializing-labels) to initialize label(LSA) on the PMEM in my VMWare vSphere virtual machine. However, I cannot properly initialize the label in a region.

VM Setting:
```
CPU 4
Memory 8 GB
NVDIMM 1 16GB
 - NVDIMM Controller
    Available persistent memory 795.95 GB
    Supported by guest 5.98 TB
    This VM has 1 NVDIMMs 16384 MB
Hard disk 1 100 GB | Thick Provision Lazy Zeroed

Compatibility | ESXi 6.7 Update 2 and later (VM version 15)
Guest OS | CentOS 8 (64-bit) | CentOS Linux release 8.0.1905 (Core)
```

I have tried with `ndctl` version 62, 67 and the latest version from `ndctl` git repo v71.1 tag: https://github.com/pmem/ndctl/tree/v71.1 
```
[root@k8s-pmem-csi ndctl-71]# ndctl --version
71+
```

Reproduce procedure and output:
1. `ndctl` list output at the beginning:
```
[root@k8s-pmem-csi ndctl-71]# ndctl list -DNR
{
  "dimms":[
    {
      "dev":"nmem0",
      "id":"8902-5f86e969",
      "handle":0,
      "phys_id":148
    }
  ],
  "regions":[
    {
      "dev":"region0",
      "size":17179869184,
      "available_size":0,
      "max_available_extent":0,
      "type":"pmem",
      "mappings":[
        {
          "dimm":"nmem0",
          "offset":0,
          "length":17179869184,
          "position":0
        }
      ],
      "persistence_domain":"memory_controller",
      "namespaces":[
        {
          "dev":"namespace0.0",
          "mode":"raw",
          "size":17179869184,
          "sector_size":512,
          "blockdev":"pmem0"
        }
      ]
    }
  ]
}
```
2. Disable region, failed to initialize label
```
[root@k8s-pmem-csi ndctl-71]# ndctl destroy-namespace -f namespace0.0
destroyed 0 namespaces
[root@k8s-pmem-csi ndctl-71]# ndctl disable-region region0
disabled 1 region
[root@k8s-pmem-csi ndctl-71]# ndctl init-labels --verbose nmem0
initialized 0 nmem
[root@k8s-pmem-csi ndctl-71]# ndctl enable-region region0
enabled 1 region
[root@k8s-pmem-csi ndctl-71]# ndctl list -RN
{
  "regions":[
    {
      "dev":"region0",
      "size":17179869184,
      "available_size":0,
      "max_available_extent":0,
      "type":"pmem",
      "persistence_domain":"memory_controller",
      "namespaces":[
        {
          "dev":"namespace0.0",
          "mode":"raw",
          "size":17179869184,
          "sector_size":512,
          "blockdev":"pmem0"
        }
      ]
    }
  ]
}
```
3. Output of check-label, read-label:
```
[root@k8s-pmem-csi ndctl-71]# ndctl check-labels nmem0
successfully verified 0 nmem label
[root@k8s-pmem-csi ndctl-71]# ndctl read-labels -u nmem0
read 0 nmem
```

Is there any wrong step? Where should I find more logs to provide more information to you? Please let me know if you need more information about the VM. Thanks!

**Comment by djbw** [comment]
Does ESXi properly emulate a label storage area for the virtual DIMM?

You can check by running:

# cat /sys/bus/nd/devices/nmem0/available_slots /sys/bus/nd/devices/nmem0/commands 

...which shows something like the following when the hypervisor implements label support:

509
get_size get_data set_data cmd_call

**Comment by Tianyang-Zhang** [comment]
Thanks for helping. The output from the command shows:
```
[root@k8s-pmem-csi ~]# cat /sys/bus/nd/devices/nmem0/available_slots /sys/bus/nd/devices/nmem0/commands
cat: /sys/bus/nd/devices/nmem0/available_slots: No such device or address
cmd_call
```

**Comment by djbw** [comment]
Yes, it looks like this vNVDIMM does not provide for a way to sub-divide capacity. However, you can still change the mode of the namespace, you just can't change the size from the VM.

ndctl create-namespace -e namespace0.0 -m fsdax -f

...will enable standard DAX operation on that label-less namespace.

**Comment by Tianyang-Zhang** [comment]
Got it. Do you know which specific version of vSphere supports LSA by any chance? I am trying to use the PMEM-CSI driver for Kubernetes, which requires LSA. Thanks!

**Comment by sscargal** [comment]
@Tianyang-Zhang I don't believe it's possible on any current ESXi version because ESXi uses a proprietary PMem Virtual File system on the host to carve out capacity for the guests, as described [here](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-93E5390A-8FCF-4CE1-8927-9FC36E889D00.html):

> **PMem Datastore**
After you add persistent memory to your ESXi host, the host detects the hardware, and then formats and mounts it as a local PMem datastore. ESXi uses VMFS-L as a file system format. Only one local PMem datastore per host is supported.

You would need to approach VMWare with the problem and work on a solution with them.

**Comment by Tianyang-Zhang** [comment]
I see. Thanks a lot for helping!
