### ISSUE TITLE
Issues using Optane DCPMM with Linux KVM (virtual machine)

### ISSUE THREAD

**Issue by kssuraaj28** [pmem/ndctl#166]
I have a server with 2x512G Intel Optane NVDIMMs. My host machine specifications are as follows:
```
Processor: Intel(R) Xeon(R) Platinum 8260L CPU @ 2.30GHz
Kernel: 5.4.0-66-generic 
OS: 18.04.2-Ubuntu
```
I want to use the host machine with `qemu-kvm` as a hypervisor to create virtual machines which have persistent memory (https://lenovopress.com/lp1224.pdf)

* I have provisioned the DIMMs as AppDirectNotInterleaved
* Using `ndctl create-namespace`, I have created 2 `/dev/pmemX` devices (`/dev/pmem0` and `/dev/pmem1`) configured in fsdax mode.
* `# mkfs.ext4 /dev/pmem0` and `# mount -o dax /dev/pmem0 /mnt/pmem0` creates and mounts an ext4 filesystem on the Linux host.
* I create a persistent file using `truncate -s 10G /mnt/pmem0/vmfile`
* To start the virtual machine, I use:
```
# qemu-system-x86_64   -m 4G,slots=4,maxmem=32G   -smp 4  \
-machine pc,accel=kvm,nvdimm=on   -enable-kvm  -vga virtio  \
-net nic   -net user,hostfwd=tcp::3001-:22  \
-object memory-backend-file,id=mem1,share,mem-path=/mnt/pmem0/vmfile,size=10G,align=2M   \
-device nvdimm,memdev=mem1,unarmed=on,id=nv1,label-size=2M   -hda qemu-disk/guest-ubuntu-install -monitor stdio                            
```
* The guest is also Ubuntu 18.04 server, running a Linux 4.15.0-136-generic kernel, with the following relevant configuration options set:
```
CONFIG_LIBNVDIMM=y 
CONFIG_BLK_DEV_PMEM=m 
CONFIG_ND_BLK=m 
CONFIG_ND_CLAIM=y 
CONFIG_ND_BTT=m 
CONFIG_BTT=y 
CONFIG_ND_PFN=m 
CONFIG_NVDIMM_PFN=y 
CONFIG_NVDIMM_DAX=y 
CONFIG_DAX=y 
CONFIG_DEV_DAX=m 
CONFIG_DEV_DAX_PMEM=m 
CONFIG_NVMEM=y 
```
* The VM shows /dev/pmem0 with a size of 10G.
* However, `# mkfs.ext4 /dev/pmem0` gives this error: `/dev/pmem0: Operation not permitted while setting up superblock`
* `ndctl destroy-namespace all` gives this error: `Error: namespace0.0: read-only, re-configuration disabled`
How can I get the virtual machines to use persistent memory in my current setup?

**Comment by djbw** [comment]
That qemu command-line is specifying "`unarmed=on`". When the guest LIBNVDIMM stack sees "unarmed" it marks the region read-only by default, because unarmed means that the platform is not ready to preserve NVDIMM contents at power-loss. Delete that "`unarmed=on`" parameter.

**Comment by kssuraaj28** [comment]
Thank you. That was the issue. It is fixed now
