### ISSUE TITLE
Make check fail on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by ironhide888** [pmem/ndctl#17]
My OS is ubuntu 16.04.2, and also upgraded kernel to 4.11.2.
When i run make check, it shows SKIP: 5 and FAIL:3. Detail of test_suit.log as following:
Is anything wrong in my environment?

**# ====================================
   ndctl 56+: test/test-suite.log
====================================

# TOTAL: 8
# PASS:  0
# SKIP:  5
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

SKIP: libndctl
==============

libkmod: DEBUG ../libkmod/libkmod.c:402 kmod_pool_get_module: get module name='nfit' found=(nil)
libkmod: DEBUG ../libkmod/libkmod.c:410 kmod_pool_add_module: add 0xa70c20 key='nfit'
libkmod: DEBUG ../libkmod/libkmod-module.c:744 kmod_module_get_path: name='nfit' path='(null)'
libkmod: DEBUG ../libkmod/libkmod.c:582 kmod_search_moddep: file=/lib/modules/4.11.2-mytest/modules.dep.bin modname=nfit
libkmod: DEBUG ../libkmod/libkmod-module.c:202 kmod_module_parse_depline: 0 dependencies for nfit
test/init: nfit_test_init: nfit.ko: appears to be production version: /lib/modules/4.11.2-mytest/kernel/drivers/acpi/nfit/nfit.ko
__ndctl_test_skip: explicit skip test_libndctl:2684
nfit_test unavailable skipping tests
libdaxctl: daxctl_unref: context 0xa6a390 released
libndctl: ndctl_unref: context 0xa6a3e0 released
attempted: 1 skipped: 1
SKIP libndctl (exit status: 77)

SKIP: dsm-fail
==============

libkmod: DEBUG ../libkmod/libkmod.c:402 kmod_pool_get_module: get module name='nfit' found=(nil)
libkmod: DEBUG ../libkmod/libkmod.c:410 kmod_pool_add_module: add 0xe94c20 key='nfit'
libkmod: DEBUG ../libkmod/libkmod-module.c:744 kmod_module_get_path: name='nfit' path='(null)'
libkmod: DEBUG ../libkmod/libkmod.c:582 kmod_search_moddep: file=/lib/modules/4.11.2-mytest/modules.dep.bin modname=nfit
libkmod: DEBUG ../libkmod/libkmod-module.c:202 kmod_module_parse_depline: 0 dependencies for nfit
test/init: nfit_test_init: nfit.ko: appears to be production version: /lib/modules/4.11.2-mytest/kernel/drivers/acpi/nfit/nfit.ko
__ndctl_test_skip: explicit skip test_dsm_fail:177
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0xe8e3e0 released
attempted: 1 skipped: 1
SKIP dsm-fail (exit status: 77)

SKIP: dpa-alloc
===============

libkmod: DEBUG ../libkmod/libkmod.c:402 kmod_pool_get_module: get module name='nfit' found=(nil)
libkmod: DEBUG ../libkmod/libkmod.c:410 kmod_pool_add_module: add 0x1354c20 key='nfit'
libkmod: DEBUG ../libkmod/libkmod-module.c:744 kmod_module_get_path: name='nfit' path='(null)'
libkmod: DEBUG ../libkmod/libkmod.c:582 kmod_search_moddep: file=/lib/modules/4.11.2-mytest/modules.dep.bin modname=nfit
libkmod: DEBUG ../libkmod/libkmod-module.c:202 kmod_module_parse_depline: 0 dependencies for nfit
test/init: nfit_test_init: nfit.ko: appears to be production version: /lib/modules/4.11.2-mytest/kernel/drivers/acpi/nfit/nfit.ko
__ndctl_test_skip: explicit skip test_dpa_alloc:304
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0x134e3e0 released
attempted: 1 skipped: 1
SKIP dpa-alloc (exit status: 77)

SKIP: parent-uuid
=================

libkmod: DEBUG ../libkmod/libkmod.c:402 kmod_pool_get_module: get module name='nfit' found=(nil)
libkmod: DEBUG ../libkmod/libkmod.c:410 kmod_pool_add_module: add 0x128dc20 key='nfit'
libkmod: DEBUG ../libkmod/libkmod-module.c:744 kmod_module_get_path: name='nfit' path='(null)'
libkmod: DEBUG ../libkmod/libkmod.c:582 kmod_search_moddep: file=/lib/modules/4.11.2-mytest/modules.dep.bin modname=nfit
libkmod: DEBUG ../libkmod/libkmod-module.c:202 kmod_module_parse_depline: 0 dependencies for nfit
test/init: nfit_test_init: nfit.ko: appears to be production version: /lib/modules/4.11.2-mytest/kernel/drivers/acpi/nfit/nfit.ko
__ndctl_test_skip: explicit skip test_parent_uuid:234
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0x12873e0 released
attempted: 1 skipped: 1
SKIP parent-uuid (exit status: 77)

SKIP: multi-pmem
================

libkmod: DEBUG ../libkmod/libkmod.c:402 kmod_pool_get_module: get module name='nfit' found=(nil)
libkmod: DEBUG ../libkmod/libkmod.c:410 kmod_pool_add_module: add 0x192ac20 key='nfit'
libkmod: DEBUG ../libkmod/libkmod-module.c:744 kmod_module_get_path: name='nfit' path='(null)'
libkmod: DEBUG ../libkmod/libkmod.c:582 kmod_search_moddep: file=/lib/modules/4.11.2-mytest/modules.dep.bin modname=nfit
libkmod: DEBUG ../libkmod/libkmod-module.c:202 kmod_module_parse_depline: 0 dependencies for nfit
test/init: nfit_test_init: nfit.ko: appears to be production version: /lib/modules/4.11.2-mytest/kernel/drivers/acpi/nfit/nfit.ko
__ndctl_test_skip: explicit skip test_multi_pmem:259
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0x19243e0 released
attempted: 1 skipped: 1
SKIP multi-pmem (exit status: 77)

FAIL: create.sh
===============

../build-aux/test-driver: line 107: ./create.sh: Permission denied
FAIL create.sh (exit status: 126)

FAIL: clear.sh
==============

../build-aux/test-driver: line 107: ./clear.sh: Permission denied
FAIL clear.sh (exit status: 126)

FAIL: dax-errors.sh
===================

../build-aux/test-driver: line 107: ./dax-errors.sh: Permission denied
FAIL dax-errors.sh (exit status: 126)**

**Comment by stellarhopper** [comment]
> test/init: nfit_test_init: nfit.ko: appears to be production version: /lib/modules/4.11.2-mytest/kernel/drivers/acpi/nfit/nfit.ko
> __ndctl_test_skip: explicit skip test_libndctl:2684
> nfit_test unavailable skipping tests

The nfit_test module is required for these unit tests, and appears not to be loaded.
See the "Unit Tests" section in README.md for how to set it up in your kernel.
