### ISSUE TITLE
pmem ndctl build issue

### ISSUE THREAD

**Issue by hiten4612** [pmem/ndctl#178]
Hi, I follow this link https://docs.pmem.io/persistent-memory/getting-started-guide/installing-ndctl for build ndctl for centOS8
BUT I see the one error at 3. Build when I fire sudo make command and my logs are

   GEN      version.m4
make --no-print-directory all-recursive
  GEN      version.m4
Making all in .
  GEN      version.m4
Making all in daxctl/lib
  GEN      libdaxctl.pc
Making all in ndctl/lib
  GEN      libndctl.pc
Making all in ndctl
make --no-print-directory all-am
  CCLD     ndctl
Making all in daxctl
make --no-print-directory all-am
make[3]: Nothing to be done for 'all-am'.
Making all in Documentation/ndctl
  GEN      ndctl.1
mv: cannot stat 'ndctl.1+': No such file or directory
make[2]: *** [Makefile:615: ndctl.1] Error 1
make[1]: *** [Makefile:804: all-recursive] Error 1
make: *** [Makefile:555: all] Error 2

Does anyone help me regarding this issue?

**Comment by sscargal** [comment]
Can you try the instructions from [https://docs.pmem.io/ndctl-user-guide/installing-ndctl/installing-ndctl-from-source-on-linux](https://docs.pmem.io/ndctl-user-guide/installing-ndctl/installing-ndctl-from-source-on-linux) instead and let me know if this works. I just updated them for CentOS 8.x/Stream as some of the requirements were moved from EPEL to the PowerTools repository. These instructions work for me on CentOS 8.4.2105.

I'll update the page you found to point to the NDCTL User Guide instructions to avoid future issues.

**Comment by hiten4612** [comment]
Thanks for the help I follow the instruction which is mention on those links But after all, I see this type of error
Also, some packages are not installed through "yum " so I use rpm to install packages (like: oxygen,kmod-devel,rubygen-asciidoctor,pandoc,etc..) so is this create any issue while make ?

I tried all these steps on Ubuntu18 and it works well , so I copy all .1 files from ubuntu to centos and then fire "sudo make"
so I see below logs

 GEN      version.m4
make --no-print-directory all-recursive
  GEN      version.m4
Making all in .
  GEN      version.m4
Making all in daxctl/lib
make[2]: Nothing to be done for 'all'.
Making all in ndctl/lib
make[2]: Nothing to be done for 'all'.
Making all in ndctl
make --no-print-directory all-am
make[3]: Nothing to be done for 'all-am'.
Making all in daxctl
make --no-print-directory all-am
make[3]: Nothing to be done for 'all-am'.
Making all in Documentation/ndctl
make[2]: Nothing to be done for 'all'.
Making all in Documentation/daxctl
make[2]: Nothing to be done for 'all'.
Making all in test
make[2]: Nothing to be done for 'all'.

so Now what is wrong here?

**Comment by sscargal** [comment]
The packages you list (oxygen,kmod-devel,rubygen-asciidoctor,pandoc,etc) are in the PowerTools repository on CentOS 8.x/CentOS Stream. On CentOS 7.x they used to live in the EPEL repository. You need to enable the PowerTools repo. Instructions can be found on [https://docs.pmem.io/ndctl-user-guide/installing-ndctl/installing-ndctl-from-source-on-linux](https://docs.pmem.io/ndctl-user-guide/installing-ndctl/installing-ndctl-from-source-on-linux). Click on the 'RHEL and CentOS' tabs and follow the 'CentOS 8.x/CentOS Stream' section.

**Comment by hiten4612** [comment]
Thanks for the support I successfully install ndctl and ipmctl library 
after that, I clone pmdk and build it from the below link 
https://github.com/pmem/pmdk/
But when i use "make check TEST_TYPE=short TEST_BUILD=debug TEST_FS=pmem" I see below type's of error log 

trace9.log below.
obj_ctl_arenas/TEST9 trace9.log {obj_ctl_arenas.c:256 main} obj_ctl_arenas/TEST9: START: obj_ctl_arenas
obj_ctl_arenas/TEST9 trace9.log  ./obj_ctl_arenas /mnt/pmem//test_obj_ctl_arenas9😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/testset1 d
obj_ctl_arenas/TEST9 trace9.log {obj_ctl_arenas.c:298 main} obj_ctl_arenas/TEST9: Error: pmemobj_create: /mnt/pmem//test_obj_ctl_arenas9😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/testset1: Invalid argument

RUNTESTS: stopping: obj_ctl_arenas/TEST9 failed, TEST=short FS=pmem BUILD=debug
obj_ctl_config/TEST0: SETUP (short/pmem/debug)
obj_ctl_config/TEST0: PASS                      [00.878 s]
obj_ctl_config/TEST1: SETUP (short/pmem/debug)
obj_ctl_config/TEST1: PASS                      [00.060 s]
obj_ctl_debug/TEST0: SETUP (short/pmem/debug)
obj_ctl_debug/TEST0: PASS                       [00.032 s]
obj_ctl_debug/TEST1: SETUP (short/pmem/debug/memcheck)
obj_ctl_debug/TEST1: PASS                       [00.628 s]
obj_ctl_debug/TEST2: SKIP Valgrind with pmemcheck required
obj_ctl_heap_size/TEST0: SETUP (short/pmem/debug)
obj_ctl_heap_size/TEST0: PASS                   [00.067 s]
obj_ctl_heap_size/TEST1: SETUP (short/pmem/debug)
obj_ctl_heap_size/TEST1: PASS                   [00.069 s]
obj_ctl_stats/TEST0: SETUP (short/pmem/debug)
obj_ctl_stats/TEST0 crashed (signal 6). err0.log below.
{obj_ctl_stats.c:52 main} obj_ctl_stats/TEST0: Error: assertion failure: ret (0xffffffffffffffff) == 0 (0x0)
err0.log below.
obj_ctl_stats/TEST0 err0.log {obj_ctl_stats.c:52 main} obj_ctl_stats/TEST0: Error: assertion failure: ret (0xffffffffffffffff) == 0 (0x0)

out0.log below.
obj_ctl_stats/TEST0 out0.log obj_ctl_stats/TEST0: START: obj_ctl_stats
obj_ctl_stats/TEST0 out0.log  ./obj_ctl_stats /mnt/pmem//test_obj_ctl_stats0😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/testfile1

trace0.log below.
obj_ctl_stats/TEST0 trace0.log {obj_ctl_stats.c:13 main} obj_ctl_stats/TEST0: START: obj_ctl_stats
obj_ctl_stats/TEST0 trace0.log  ./obj_ctl_stats /mnt/pmem//test_obj_ctl_stats0😘⠏⠍⠙⠅ɗPMDKӜ⥺🙋/testfile1
obj_ctl_stats/TEST0 trace0.log {obj_ctl_stats.c:52 main} obj_ctl_stats/TEST0: Error: assertion failure: ret (0xffffffffffffffff) == 0 (0x0)

RUNTESTS: stopping: obj_ctl_stats/TEST0 failed, TEST=short FS=pmem BUILD=debug
obj_ctl_stats/TEST1: SKIP Valgrind with pmemcheck required
obj_layout/TEST0: SETUP (short/pmem/debug)
obj_layout/TEST0: PASS                  [00.005 s]
obj_zones/TEST0: all valgrind tests disabled
obj_zones/TEST1: all valgrind tests disabled
blk_rw/TEST21: SKIP: Only supported on ppc64
blk_rw_mt/TEST0: SETUP (short/pmem/debug)
blk_rw_mt/TEST0: PASS                   [00.045 s]
ctl_prefault/TEST0: SETUP (short/pmem/debug)
ctl_prefault/TEST0: SKIP: filesystem does not support fallocate
ctl_prefault/TEST1: SETUP (short/pmem/debug)
ctl_prefault/TEST1: SKIP: filesystem does not support fallocate
ctl_prefault/TEST2: SETUP (short/pmem/debug)
ctl_prefault/TEST2: SKIP: filesystem does not support fallocate
util_ctl/TEST0: SETUP (short/pmem/debug)
util_ctl/TEST0: PASS                    [00.008 s]
util_pool_hdr/TEST0: SETUP (short/pmem/debug)
util_pool_hdr/TEST0: PASS                       [00.004 s]
4 tests failed:
obj_ctl_arenas/TEST7
obj_ctl_arenas/TEST8
obj_ctl_arenas/TEST9
obj_ctl_stats/TEST0
make: *** [Makefile:431: check] Error 1

So is this a library issue or pmem configuration issue?

Also when I use " sudo ipmctl show -dimm" , output is like

DimmID | Capacity  | LockState | HealthState  | FWVersion
===========================================================
 0x0000 | 0.000 GiB | Unknown   | Unmanageable | N/A
 0x1110 | 0.000 GiB | Unknown   | Unmanageable | N/A

I config pmem using below commands

-> ndctl create-namespace --force --reconfig=namespace0.0 --mode=fsdax --map=mem

-> mkfs -t xfs /dev/pmem0
-> mount -o dax /dev/pmem0 /mnt/pmem/

**Comment by sscargal** [comment]
I recommend posting the PMDK issue to the [PMDK GitHub Issues](https://github.com/pmem/pmdk/issues) page, the #pmem Slack Channel ([Join here](https://join.slack.com/t/pmem-io/shared_invite/enQtNzU4MzQ2Mzk3MDQwLWQ1YThmODVmMGFkZWI0YTdhODg4ODVhODdhYjg3NmE4N2ViZGI5NTRmZTBiNDYyOGJjYTIyNmZjYzQxODcwNDg)), or the [PMem Forum](https://groups.google.com/forum/#!forum/pmem). 

For the ipmctl issue, do you have Intel Optane Persistent Memory physically installed in the system? ipmctl only works with Intel PMem modules. If you're running this environment within a guest VM or emulating PMem, ipmctl won't work.
