### ISSUE TITLE
region0 not support 'align' for dax mode error with kernel 4.11.3

### ISSUE THREAD

**Issue by djbw** [pmem/ndctl#18]
Krishna notes:

We are getting the error below using pmem with linux kernel 4.11.3 and DAX as seen below.
Any help in this is appreciated.

root@50005:/lib/modules/4.11.3/kernel/drivers/dax# ndctl list {
"dev":"namespace0.0",
"mode":"raw",
"size":8589934592,
"blockdev":"pmem0" 
}

root@50005:/lib/modules/4.11.3/kernel/drivers/dax# ndctl create-namespace --mode dax -e namespace0.0 -f -v
libndctl: __sysfs_device_parse: base: /sys/class/nd dev: ndctl
libndctl: __sysfs_read_attr: failed to open /sys/class/nd/ndctl0/device/nfit/revision: No such file or directory
libndctl: __sysfs_device_parse: ndctl0: processed
libndctl: __sysfs_device_parse: base: /sys/devices/platform/e820_pmem/ndbus0 dev: region
libndctl: to_module: failed to find module for alias: nd:t2 0 list: empty
libndctl: __sysfs_device_parse: region0: processed
libndctl: __sysfs_device_parse: base: /sys/devices/platform/e820_pmem/ndbus0/region0 dev: namespace0.
libndctl: to_module: alias: nd:t4 module: nd_pmem
libndctl: __sysfs_device_parse: namespace0.0: processed
libndctl: __sysfs_device_parse: base: /sys/devices/platform/e820_pmem/ndbus0/region0 dev: pfn0.
libndctl: __sysfs_device_parse: base: /sys/devices/platform/e820_pmem/ndbus0/region0 dev: dax0.
validate_namespace_options:511: region0 not support 'align' for dax mode
failed to reconfigure namespace: no suitable capacity found

Part of kernel configuration is shown below -

CONFIG_TRANSPARENT_HUGEPAGE=y
CONFIG_DEV_DAX=m
CONFIG_NVDIMM_DAX=y
CONFIG_BLK_DEV_RAM_DAX=y
CONFIG_FS_DAX=y
CONFIG_X86_PMEM_LEGACY=y
CONFIG_LIBNVDIMM=y
CONFIG_NVDIMM_PFN=y
CONFIG_NVDIMM_DAX=y
CONFIG_BLK_DEV_PMEM=m
CONFIG_ARCH_HAS_PEM_API=y

**Comment by kharathi** [comment]
root@50005:/lib/modules/4.11.3/kernel/drivers/dax# tree /sys/bus/nd/devices/region0/ -I power
/sys/bus/nd/devices/region0/
|-- btt0.0
|   |-- devtype
|   |-- modalias
|   |-- namespace
|   |-- numa_node
|   |-- sector_size
|   |-- size
|   |-- subsystem -> ../../../../../../bus/nd
|   |-- uevent
|   `-- uuid
|-- btt_seed
|-- dax_seed
|-- devtype
|-- driver -> ../../../../../bus/nd/drivers/nd_region
|-- init_namespaces
|-- mappings
|-- modalias
|-- namespace0.0
|   |-- block
|   |   `-- pmem0
|   |       |-- alignment_offset
|   |       |-- badblocks
|   |       |-- bdi -> ../../../../../../../virtual/bdi/259:0
|   |       |-- capability
|   |       |-- dev
|   |       |-- device -> ../../../namespace0.0
|   |       |-- discard_alignment
|   |       |-- ext_range
|   |       |-- holders
|   |       |-- inflight
|   |       |-- queue
|   |       |   |-- add_random
|   |       |   |-- chunk_sectors
|   |       |   |-- dax
|   |       |   |-- discard_granularity
|   |       |   |-- discard_max_bytes
|   |       |   |-- discard_max_hw_bytes
|   |       |   |-- discard_zeroes_data
|   |       |   |-- hw_sector_size
|   |       |   |-- io_poll
|   |       |   |-- io_poll_delay
|   |       |   |-- iostats
|   |       |   |-- logical_block_size
|   |       |   |-- max_discard_segments
|   |       |   |-- max_hw_sectors_kb
|   |       |   |-- max_integrity_segments
|   |       |   |-- max_sectors_kb
|   |       |   |-- max_segment_size
|   |       |   |-- max_segments
|   |       |   |-- minimum_io_size
|   |       |   |-- nomerges
|   |       |   |-- nr_requests
|   |       |   |-- optimal_io_size
|   |       |   |-- physical_block_size
|   |       |   |-- read_ahead_kb
|   |       |   |-- rotational
|   |       |   |-- rq_affinity
|   |       |   |-- scheduler
|   |       |   |-- stats
|   |       |   |-- wbt_lat_usec
|   |       |   |-- write_cache
|   |       |   |-- write_same_max_bytes
|   |       |   |-- write_zeroes_max_bytes
|   |       |   `-- zoned
|   |       |-- range
|   |       |-- removable
|   |       |-- ro
|   |       |-- size
|   |       |-- slaves
|   |       |-- stat
|   |       |-- subsystem -> ../../../../../../../../class/block
|   |       |-- trace
|   |       |   |-- act_mask
|   |       |   |-- enable
|   |       |   |-- end_lba
|   |       |   |-- pid
|   |       |   `-- start_lba
|   |       `-- uevent
|   |-- devtype
|   |-- driver -> ../../../../../../bus/nd/drivers/nd_pmem
|   |-- force_raw
|   |-- holder
|   |-- modalias
|   |-- mode
|   |-- nstype
|   |-- numa_node
|   |-- resource
|   |-- size
|   |-- subsystem -> ../../../../../../bus/nd
|   `-- uevent
|-- namespace_seed
|-- nstype
|-- pfn_seed
|-- read_only
|-- size
|-- subsystem -> ../../../../../bus/nd
`-- uevent

16 directories, 81 files

**Comment by djbw** [comment]
If I take a look at the region0 sysfs layout on a known good configuration I see:

# tree region0 -L 1
region0
├── badblocks
├── btt0.0
├── btt_seed
├── dax0.0
├── dax_seed
├── devtype
├── driver -> ../../../../../bus/nd/drivers/nd_region
├── init_namespaces
├── mappings
├── modalias
├── namespace0.0
├── namespace_seed
├── nstype
├── pfn0.0
├── pfn_seed
├── power
├── read_only
├── resource
├── size
├── subsystem -> ../../../../../bus/nd
└── uevent

It looks like 'pfn' devices and 'dax' devices are missing. Are you sure you enabled the following config symbols:

CONFIG_LIBNVDIMM=m
CONFIG_BLK_DEV_PMEM=m
CONFIG_ND_BLK=m
CONFIG_ND_CLAIM=y
CONFIG_ND_BTT=m
CONFIG_BTT=y
CONFIG_ND_PFN=m
CONFIG_NVDIMM_PFN=y
CONFIG_NVDIMM_DAX=y
CONFIG_DAX=y
CONFIG_DEV_DAX=m
CONFIG_DEV_DAX_PMEM=m

**Comment by djbw** [comment]
I believe this has been root caused to a misconfigured kernel, please re-open if you continue to see problems.
