### ISSUE TITLE
Data erase after reset pmem

### ISSUE THREAD

**Issue by hiten4612** [pmem/ndctl#180]
First, I mount pmem0 using the below command
Sudo mount /dev/pmem0 /mnt/dax

Then after I use Pmdk library libpmem/manpage.c
change the PATH = /mnt/dax/first.txt
and run the code 

So There is first.txt file is created in /mnt/dax location with some string data.BUT After reboot(power reset) /mnt/dax location is empty my first.txt created file is deleted So what's happened here?

**Comment by sscargal** [comment]
@hiten4612 Is the /dev/pmem0 device mounted automatically at boot? By default, it is not.

**Comment by hiten4612** [comment]
No, I manually mount every time after reboot.

**Comment by sscargal** [comment]
There's nothing special about the manpage.c example. It memory-maps a file, writes a string, then closes/unmaps the file. If you unmount /mnt/dax and check if `/mnt/dax/first.txt` exists, you can determine if you accidentally ran your experiment without the NVDIMM-N mounted. This is the most common cause. 

If you copy a file to the NVDIMM-N backed file system and reboot, is the data there or not?, eg:

```
// Assumes the /mnt/pmem0 is mounted
$ df -h /mnt/dax
$ sudo cp /var/log/messages /mnt/dax
$ ls -h /mnt/dax/messages
$ sudo systemctl reboot

// Mount the file system & confirm
$ sudo mount /dev/pmem0 /mnt/dax
$ df -h /mnt/dax

// Check dmesg for any errors reported at mount time
$ sudo dmesg 

// Check if the data exists
$ ls -h /mnt/dax/messages
```

If the data doesn't exist, then the NVDIMM-N isn't saving the data. In that scenario, I would also expect the filesystem to not exist after a reboot or have some corruption/fsck issues. 

We should move this discussion to the [Forums ](https://groups.google.com/g/pmem) as it's not an ndctl issue.

**Comment by hiten4612** [comment]
Hello, I Don't know but after some read-write, My pmem0 is write-protected.

mount  /dev/pmem0 /mnt/nvme/
mount: /dev/pmem0 is write-protected, mounting read-only
mount: unknown filesystem type '(null)'

**Comment by sscargal** [comment]
Check your BIOS and Hardware logs for errors. There's a few documented scenarios where the HW will write-protect the NVDIMM-Ns. See "[Dell EMC NVDIMM-N Persistent Memory User Guide](https://www.dell.com/support/manuals/en-us/poweredge-t640/nvdimm-n_ug_pub/bios-error-messages)". Open a support call with your hardware vendor for further assistance.
