### ISSUE TITLE
How to reset pmem address space?

### ISSUE THREAD

**Issue by hiten4612** [pmem/ndctl#182]
I am using Dell EMC NVDIMM-N Persistent Memory with PowerEdge R740 with centos 8
In this system, pmem0 node present at /dev directory 

ndctl list
[
  {
    "dev":"namespace0.0",
    "mode":"fsdax",
    "map":"dev",
    "size":16909336576,
    "uuid":"c8faa04f-7f6a-4794-b269-344b6804bbaf",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem0"
  }
]

Then I created one pmem0p1 partition around 50mb
Disk /dev/pmem0: 16.9 GB, 16909336576 bytes, 33026048 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disk label type: gpt
Disk identifier: 125CFD7E-D40F-4C8E-9738-4FE03F6EB845
#         Start          End    Size  Type            Name
 1         2048       112233   53.8M  Linux filesystem

I write the data using mmap
off_t address = 0x100000;
int width = 10;
unsigned  char  *virtladdr, *phyaddr;
char a[100] ="12345678";
char *lendata = &a;
char str2[] = "Quiz";
int main(void)
{
         int mode = 0x0777;
        char *filename = "/dev/pmem0p1";
        int fdout;
         if ((fdout = open (filename, O_RDWR | O_CREAT | O_TRUNC, mode )) < 0)//edited here
           {
                   printf ("can't create file");
            return 0;
}

And there read this data using below code
off_t address = 0x100000;
int width = 10;
int main(void)
{
        int retVal = -1;
        int fd;
        unsigned long mapped_size, page_size, offset_in_page;
    void *virtladdr, *phyaddr;

        fd = open("/dev/pmem0p1", O_RDWR | O_SYNC);
    if(fd < 0)
        {
                printf("file not open \n");
        }

then after read-write operation, I reboot the system (ALSO power on/off pmem)

first time I got the data 12345678)
Now I change data(203040506) and then reboot the system 
The second time I got new data (203040506)
But The Issue is when I write a third time to my pmem with a new data string i got Previous data(203040506). so somehow my pmem memory is looked. no new changes are applied to those address locations. I tried memset() but not work. so what should I do?

**Comment by sscargal** [comment]
@hiten4612 Please re-ask your question on the [PMem forum](https://groups.google.com/g/pmem?pli=1) or [join the #pmem Slack Channel](https://join.slack.com/t/pmem-io/shared_invite/enQtNzU4MzQ2Mzk3MDQwLWQ1YThmODVmMGFkZWI0YTdhODg4ODVhODdhYjg3NmE4N2ViZGI5NTRmZTBiNDYyOGJjYTIyNmZjYzQxODcwNDg). This issue is unrelated to ndctl, so you won't find an answer here. Thanks.
