### ISSUE TITLE
ndctl shows all devices with temp 255

### ISSUE THREAD

**Issue by boyadzhievb** [pmem/ndctl#185]
[root@host ~]# ndctl list -H -D
[
  {
    "dev":"nmem11",
    "id":"802c-0f-2008-26a3e62f",
    "handle":4385,
    "phys_id":4375,
    "health":{
      "health_state":"ok",
      "temperature_celsius":255.000000,
      "life_used_percentage":5
    }
  },
  {
    "dev":"nmem10",
    "id":"802c-0f-2008-26a3e382",
    "handle":4369,
    "phys_id":4374,
    "health":{
      "health_state":"ok",
      "temperature_celsius":255.000000,
      "life_used_percentage":6
    }
  },

**Comment by sscargal** [comment]
@boyadzhievb Given the lack of health stats, are you using NVDIMM-N's? NVDIMM-N devices have no SMART data, which would explain the results. Optane PMem 100 and 200 Series have a wealth of health stats. 

Please provide more information about your environment:

- What Linux distribution and version are you using? 
- What Kernel version do you have? (`uname -a`)
- What Server are you using? (`dmidecode -t baseboard`)
- What NVDIMM are you using? (Optane PMem or NVDIMM-N) - (`dmidecode -t memory`)
- How many PMem/NVDIMM modules do you have installed? (12?)

We can gather more info should we need to.

**Comment by boyadzhievb** [comment]
Yes , devices are NVDIMM-N, you can close this issue, obvious temp is not supported. Thank you.
