### ISSUE TITLE
duplicated monitor configuration installed

### ISSUE THREAD

**Issue by hramrach** [pmem/ndctl#189]
After installing v72 I have two copies of monitor configuration:

/etc/ndctl.conf.d/monitor.conf has monitor configuration without any sections
/etc/ndctl.conf.d/ndctl.conf has monitor configuration inside [monitor] section

There is no description how these files are supposed to work together so I suspect they don't.

**Comment by djbw** [comment]
Was this from make install from source, or from a distribution package?

**Comment by hramrach** [comment]
Distribution packages are also installed from source, you know?

The /etc/ndctl.conf.d/ directory is new in v72 (v72.1 more precisely) so there is no way the package would suddenly fabricate files there.

**Comment by djbw** [comment]
True, sorry for that noise. I was thinking that we'll also need to detect existing monitor.conf instances in our sample spec file. The intent is that all conf files in the ndctl.conf.d are aggregated together, so only one of them is needed. @stellarhopper is there support for monitor configuration without putting it in a [monitor] section?

**Comment by djbw** [comment]
I think legacy monitor.conf should stay in /etc/ndctl where it can exist withtout needing a [monitor] section and only new-style configuration goes in /etc/ndctl.conf.d.

**Comment by hramrach** [comment]
At any only one copy if the configuration should be shipped.

And the question of how this works together still remains.

**Comment by djbw** [comment]
Yes, I expect "ndctl monitor" needs to search /etc/ndctl/monitor.conf first, and then merge that with any [monitor] sections that may appear in any file in /etc/ndctl.conf.d.

**Comment by hramrach** [comment]
That would work. So long as the identical monitor.conf is shipped in old location any changes will be preserved on upgrade, and because the default sample file does not set anything they would be effective as well.

**Comment by hramrach** [comment]
but how does it work with -c?

Does that override the legacy file? The new file? Both? Does it take conf.d directory path or full file path?

**Comment by hramrach** [comment]
There is also the option to abandon the old style file and merge the old style file content into the conf.d directory on upgrade.

It would help to ship per-component conf.d file rather than one big file then, too.
