### ISSUE TITLE
create-namespace -m devdax  Error reporting

### ISSUE THREAD

**Issue by yanglongkanglo** [pmem/ndctl#204]
[root@localhost ~]# ndctl --version
71.1
[root@localhost ~]# ndctl create-namespace -m devdax -a 2M -r region0
libndctl: ndctl_dax_enable: dax0.0: failed to enable
  Error: namespace0.0: failed to enable

failed to create namespace: No such device or address
[root@localhost ~]# uname -r
5.10.0

**Comment by yanglongkanglo** [comment]
@sscargal Can you help me look at this?

**Comment by sscargal** [comment]
@yanglongkanglo Can you describe your environment please?

Q) What Operating System do you have installed? (`cat /etc/os-release`)
Q) Is this a bare-metal, Virtual Machine, or Container environment?
Q) Do you have physical PMem installed, or are you emulating it with QEMU or the Kernel memmap option?

Q) What regions do you have? (`ndctl list -R`)
Q) What active/inactive namespaces do you have? (`ndctl list -Ni`)
Q) If you have physical Intel Optane [100|200] PMem installed, can you collect `ipmctl show -dimm`, `ipmctl show -region`, `ipmctl show -memoryresources`
Q) What do you see in dmesg or /var/log/messages around the time you ran the `ndctl create-namespace -m devdax -a 2M -r region0` command?
Q) What do you see if you add the `--verbose` (-v) option to the `ndctl create-namespace -m devdax -a 2M -r region0` command? ie: `ndctl create-namespace -m devdax -a 2M -r region0 --verbose`

**Comment by hramrach** [comment]
Also please try with current version.

**Comment by yanglongkanglo** [comment]
I found a problem with my machine.
I tried using `lsmod |grep dax_pmem` and `modprobe dax_pmem`，and it worked fine.
Thank you for your reply，it really useful for me@[sscargal](https://github.com/sscargal) and [hramrach](https://github.com/hramrach)
