### ISSUE TITLE
ndctl not show the dimm information

### ISSUE THREAD

**Issue by norjar** [pmem/ndctl#21]
My machine has two 8G NVDIMMs and OS is SUSE with kernel v4.4.21.
I try to use the ndctl to manage them, but something goes wrong.
The information below is provided by this tool.
```
linux-4o54:/home/viking # ndctl list -BiRN
{
  "provider":"e820",
  "dev":"ndbus0",
  "regions":[
    {
      "dev":"region0",
      "size":17179869184,
      "available_size":0,
      "type":"pmem",
      "namespaces":[
        {
          "dev":"namespace0.0",
          "mode":"memory",
          "size":17179869184,
          "blockdev":"pmem0"
        }
      ]
    }
  ]
}
```
Howerver, when I try to use `ndctl list --dimms` to show the dimm information, the ndctl shows nothing for me.

Additionally, I want to reconfigure namespace,  so I try to destroy the current one.
After I execute the "destroy" command, I can still enable the "destroyed" namespace.
```
linux-4o54:/home/viking # ndctl list --namespaces
{
  "dev":"namespace0.0",
  "mode":"memory",
  "size":17179869184,
  "blockdev":"pmem0"
}
linux-4o54:/home/viking # ndctl disable-namespace namespace0.0 
disabled 1 namespace
linux-4o54:/home/viking # ndctl destroy-namespace all
destroyed 1 namespace
linux-4o54:/home/viking # ndctl list --namespaces
linux-4o54:/home/viking # ndctl list --regions
{
  "dev":"region0",
  "size":17179869184,
  "available_size":0,
  "type":"pmem"
}
linux-4o54:/home/viking # ndctl enable-namespace namespace0.0 
enabled 1 namespace
```

Finally, as we can see above, we only have one region, so does it means that the NVDIMMs only support "PMEM" type?

**Comment by djbw** [comment]
You are on a platform that does not provide an NFIT ("provider":"e820"), so Linux has no information about the NVDIMMs, it only has an address range. You would need a BIOS update from your vendor to see DIMM information.

The ndctl destroy-namespace behavior is expected for DIMM devices that do not export labels. There are no labels to destroy. However destroy will remove any info blocks, so if you had placed the namespace into "sector" mode it would revert back to its default mode.namespace.

Yes, in the '"provider":"e820"' case only PMEM is supported.

**Comment by norjar** [comment]
Thanks, but I do not understand your explain about the ndctl destroy-namespace behavior. I know this tool by this two blogs, [NVDIMM Enabling in SUSE Linux Enterprise 12, Service Pack 2](https://www.suse.com/communities/blog/nvdimm-enabling-suse-linux-enterprise-12-service-pack-2/) and [NVDIMM Enabling – Part 2 by Intel](https://www.suse.com/communities/blog/nvdimm-enabling-part-2-intel/). Could you give me some other reference about this ndctl tool.

**Comment by djbw** [comment]
The "destroy-namespace" command only writes zeroes the namespace label information and any information blocks on the namespace. It does not permanently remove the namespace. Especially in your case where the platform does not support labels. When the namespace is defined on a "e820" bus. It cannot be fully destroyed. I'll go ahead and add these details to the "ndctl destroy-namespace" man page.

**Comment by norjar** [comment]
Thanks. Therefore, I should firstly update my BIOS from vendor.
