### ISSUE TITLE
Install libnvdimm fail

### ISSUE THREAD

**Issue by ironhide888** [pmem/ndctl#22]
Hi,
1. I download kernel with the command
**git clone -b libnvdimm-for-next git://git.kernel.org/pub/scm/linux/kernel/git/nvdimm/nvdimm.git**
2. Copy my .config into libnvdimm directory, and reconfigure .config manually to match the following setting
**CONFIG_ZONE_DEVICE=y
CONFIG_LIBNVDIMM=m
CONFIG_BLK_DEV_PMEM=m
CONFIG_ND_BLK=m
CONFIG_BTT=y
CONFIG_NVDIMM_PFN=y
CONFIG_NVDIMM_DAX=y**

3. make M=tools/testing/nvdimm, and get the following message:

  CC [M]  tools/testing/nvdimm/config_check.o
In file included from ./include/asm-generic/bug.h:4:0,
                       from ./arch/x86/include/asm/bug.h:81,
                       from ./include/linux/bug.h:4,
                       from tools/testing/nvdimm/config_check.c:1:
tools/testing/nvdimm/config_check.c: In function ‘check’:
./include/linux/compiler.h:529:38: error: call to ‘__compiletime_assert_9’ declared with attribute error: BUILD_BUG_ON failed: !IS_MODULE(CONFIG_LIBNVDIMM)
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                      ^
./include/linux/compiler.h:512:4: note: in definition of macro ‘__compiletime_assert’
    prefix ## suffix();    \
    ^~~~~~
./include/linux/compiler.h:529:2: note: in expansion of macro ‘_compiletime_assert’
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
  ^~~~~~~~~~~~~~~~~~~
./include/linux/bug.h:54:37: note: in expansion of macro ‘compiletime_assert’
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^~~~~~~~~~~~~~~~~~
./include/linux/bug.h:78:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
  BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
  ^~~~~~~~~~~~~~~~
tools/testing/nvdimm/config_check.c:9:2: note: in expansion of macro ‘BUILD_BUG_ON’
  BUILD_BUG_ON(!IS_MODULE(CONFIG_LIBNVDIMM));
  ^~~~~~~~~~~~
scripts/Makefile.build:302: recipe for target 'tools/testing/nvdimm/config_check.o' failed
make[1]: *** [tools/testing/nvdimm/config_check.o] Error 1
Makefile:1512: recipe for target '_module_tools/testing/nvdimm' failed
make: *** [_module_tools/testing/nvdimm] Error 2

It seems that the setting CONFIG_LIBNVDIMM is not be "m". But i pretty sure it is be "m" in .config.
Is anything wrong in the process?

**Comment by djbw** [comment]
There are are other configuration symbols like CONFIG_X86_PMEM_LEGACY and CONFIG_ACPI_NFIT that force enable CONFIG_LIBNVDIMM. So, you need to use menuconfig or similar to setup the config, manual edits to the .config may be overwritten.

**Comment by ironhide888** [comment]
The settings in my .config are "CONFIG_X86_PMEM_LEGACY=y and CONFIG_ACPI_NFIT=m". So, i changed them to "m" or "y", and got error result as before.
 
I searched "LIBNVDIMM" in all directory, found that
#define CONFIG_LIBNVDIMM 1 in ./include/generated/autoconf.h @line 2998
CONFIG_LIBNVDIMM=Y in ./include/config/tristate.conf @line 2076

So i tried to another way.
I recover "CONFIG_X86_PMEM_LEGACY=y and CONFIG_ACPI_NFIT=m" in .config and chang the two setting manually as following:
#define CONFIG_LIBNVDIMM**_MODULE** 1 in ./include/generated/autoconf.h @line 2998
CONFIG_LIBNVDIMM=**M** in ./include/config/tristate.conf @line 2076

The error is gone. But some files are not generated normally. 
 LD      tools/testing/nvdimm/built-in.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/core.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/bus.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/dimm_devs.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/dimm.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/region_devs.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/region.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/namespace_devs.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/label.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/claim.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/btt_devs.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/pfn_devs.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/dax_devs.o
  CC [M]  tools/testing/nvdimm/config_check.o
  LD [M]  tools/testing/nvdimm/libnvdimm.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/pmem.o
  CC [M]  tools/testing/nvdimm/pmem-dax.o
  LD [M]  tools/testing/nvdimm/nd_pmem.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/btt.o
  LD [M]  tools/testing/nvdimm/nd_btt.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/blk.o
  LD [M]  tools/testing/nvdimm/nd_blk.o
  CC [M]  tools/testing/nvdimm/../../../drivers/nvdimm/e820.o
  LD [M]  tools/testing/nvdimm/nd_e820.o
  CC [M]  tools/testing/nvdimm/../../../drivers/acpi/nfit/core.o
  CC [M]  tools/testing/nvdimm/../../../drivers/acpi/nfit/mce.o
  LD [M]  tools/testing/nvdimm/nfit.o
  CC [M]  tools/testing/nvdimm/../../../drivers/dax/device.o
  CC [M]  tools/testing/nvdimm/dax-dev.o
  LD [M]  tools/testing/nvdimm/device_dax.o
  CC [M]  tools/testing/nvdimm/../../../drivers/dax/pmem.o
  LD [M]  tools/testing/nvdimm/dax_pmem.o
  LD      tools/testing/nvdimm/test/built-in.o
  CC [M]  tools/testing/nvdimm/test/nfit.o
  LD [M]  tools/testing/nvdimm/test/nfit_test.o
  CC [M]  tools/testing/nvdimm/test/iomap.o
  LD [M]  tools/testing/nvdimm/test/nfit_test_iomap.o
  Building modules, stage 2.
  MODPOST 10 modules
**WARNING: "put_dax" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "blk_freeze_queue_start" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "dax_get_private" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "kill_dax" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "alloc_dax" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "refcount_inc" [tools/testing/nvdimm/libnvdimm.ko] undefined!
WARNING: "refcount_dec_and_test" [tools/testing/nvdimm/libnvdimm.ko] undefined!
WARNING: "kvmalloc_node" [tools/testing/nvdimm/libnvdimm.ko] undefined!
WARNING: "refcount_inc" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "inode_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "vmf_insert_pfn_pud" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_alive" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "refcount_dec_and_test" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "put_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_read_lock" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_get_private" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_inode" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_read_unlock" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "kill_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "cdev_device_add" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "alloc_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "cdev_device_del" [tools/testing/nvdimm/device_dax.ko] undefined!**
  CC      tools/testing/nvdimm/dax_pmem.mod.o
  LD [M]  tools/testing/nvdimm/dax_pmem.ko
  CC      tools/testing/nvdimm/device_dax.mod.o
  LD [M]  tools/testing/nvdimm/device_dax.ko
  CC      tools/testing/nvdimm/libnvdimm.mod.o
  LD [M]  tools/testing/nvdimm/libnvdimm.ko
  CC      tools/testing/nvdimm/nd_blk.mod.o
  LD [M]  tools/testing/nvdimm/nd_blk.ko
  CC      tools/testing/nvdimm/nd_btt.mod.o
  LD [M]  tools/testing/nvdimm/nd_btt.ko
  CC      tools/testing/nvdimm/nd_e820.mod.o
  LD [M]  tools/testing/nvdimm/nd_e820.ko
  CC      tools/testing/nvdimm/nd_pmem.mod.o
  LD [M]  tools/testing/nvdimm/nd_pmem.ko
  CC      tools/testing/nvdimm/nfit.mod.o
  LD [M]  tools/testing/nvdimm/nfit.ko
  CC      tools/testing/nvdimm/test/nfit_test.mod.o
  LD [M]  tools/testing/nvdimm/test/nfit_test.ko
  CC      tools/testing/nvdimm/test/nfit_test_iomap.mod.o
  LD [M]  tools/testing/nvdimm/test/nfit_test_iomap.ko

And of course can't install...

Another weird thing is CONFIG_LIBNVDIMM is changed to **"m"** in .config by myself. If i use command "make menuconfig" to load .config and save to .config directly. CONFIG_LIBNVDIMM will be **"y"** after the process.
The menuconfig seems to load default or my environment setting, and ignores manual setting. Does it make LIBNVDIMM in ./include/generated/autoconf.h and ./include/config/tristate.conf be "Y"?

**Comment by djbw** [comment]
Yes, that it is expected. The kernel build re-validates the config file and changes manual settings. For example, if you set CONFIG_ACPI_NFIT=y (which selects CONFIG_LIBNVDIMM) it does not matter if you manually set CONFIG_LIBNVDIMM=m in the .config.  The build process will evaluate the "select" statement and force CONFIG_LIBNVDIMM=y to satisfy the dependency. I've attached the config I use for testing so you can use it as a starting point.
[config.txt](https://github.com/pmem/ndctl/files/1116059/config.txt)

**Comment by ironhide888** [comment]
Thanks!

Doesn't it matter for the following WARNING messages after execute "make M=tools/testing/nvdimm"?

**WARNING: "put_dax" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "blk_freeze_queue_start" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "dax_get_private" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "kill_dax" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "alloc_dax" [tools/testing/nvdimm/nd_pmem.ko] undefined!
WARNING: "refcount_inc" [tools/testing/nvdimm/libnvdimm.ko] undefined!
WARNING: "refcount_dec_and_test" [tools/testing/nvdimm/libnvdimm.ko] undefined!
WARNING: "kvmalloc_node" [tools/testing/nvdimm/libnvdimm.ko] undefined!
WARNING: "refcount_inc" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "inode_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "vmf_insert_pfn_pud" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_alive" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "refcount_dec_and_test" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "put_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_read_lock" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_get_private" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_inode" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "dax_read_unlock" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "kill_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "cdev_device_add" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "alloc_dax" [tools/testing/nvdimm/device_dax.ko] undefined!
WARNING: "cdev_device_del" [tools/testing/nvdimm/device_dax.ko] undefined!**

After do "sudo make M=tools/testing/nvdimm modules_install", i get following:

  **INSTALL tools/testing/nvdimm/dax_pmem.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/device_dax.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/libnvdimm.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/nd_blk.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/nd_btt.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/nd_e820.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/nd_pmem.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/nfit.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/test/nfit_test.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL tools/testing/nvdimm/test/nfit_test_iomap.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175

- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.12.0-rc4+**

Google the messages and get that the kernel module in new Ubuntu version need to be signed.
1. I try to disable secure boot in security option of BIOS. -> It still gets the above error messages.
2. Write DKMS script as attached file. And get following.
[dkms.conf.txt](https://github.com/pmem/ndctl/files/1118997/dkms.conf.txt)

**DKMS make.log for libnvdimm-1.1 for kernel 4.10.0-24-generic (x86_64)
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/basic/bin2c
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
scripts/kconfig/Makefile:37: recipe for target 'silentoldconfig' failed
make[2]: *** [silentoldconfig] Error 1
Makefile:548: recipe for target 'silentoldconfig' failed
make[1]: *** [silentoldconfig] Error 2
make: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
make: *** Waiting for unfinished jobs....
  HYPERCALLS arch/x86/entry/syscalls/../../include/generated/asm/xen-hypercalls.h**

The error shows that .config is not found. But i have confirmed both .config and dkms.conf put in root directory of nvdimm. 
Does the process or dkms.conf file wrong?

**Comment by djbw** [comment]
Make sure you have all the Ubuntu dependencies to build a kernel. Looks like you are missing SSL development headers:

sudo apt-get build-dep linux-image-$(uname -r)

**Comment by ironhide888** [comment]
Solved already. I use "make certs" to generate "signing_key.pem" file.
