### ISSUE TITLE
Query about ndctl "memory" mode

### ISSUE THREAD

**Issue by fengyuleidian0615** [pmem/ndctl#23]
Hi

There are some description in the https://nvdimm.wiki.kernel.org/ that I'm confused a bit.
As for the "_memory - /dev/pmemN block device supporting PCIe device DMA_", what's the scenario of supporting PCIe DMA?  and how?

Thanks!

![1](https://user-images.githubusercontent.com/11497776/27812161-52539d4c-609f-11e7-8697-1623481f2c8a.png)

**Comment by djbw** [comment]
See a deeper description of "memory" mode in this presentation starting at slide 15:

http://events.linuxfoundation.org/sites/events/files/slides/Managing%20Persistent%20Memory_0.pdf

**Comment by fengyuleidian0615** [comment]
Hi @djbw
Thanks for your reply! 
I read through the digram on p18 as following, 
![2](https://user-images.githubusercontent.com/11497776/27905247-00023e3e-6272-11e7-8b7c-d27d105135a6.png)

By my understanding, the scenario depicting here is copying file from dax pmem disk to legacy disk like SSD, the problem here is how to convert "buf" address into struct page,  and I read through the background of "Direct IO and DMA for persistent memory" on this [link](https://lwn.net/Articles/672457/) at lwn, tby my limited kernel knowledge, it seems memory manage system and dma subsystem is also changed for this feature requirement, I haven't dig the code more deeper, but I can not get it what's there between the start of pfn and its offset when looking at how it's actually calculated [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/nvdimm/pfn_devs.c?h=v4.12#n636), especially when I saw how [pmem_direct_access](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/nvdimm/pmem.c?h=v4.12#n204) return flagged pfn, it does read something between start of pfn and its offset.

Maybe too simple/naive question for you, but I have to ask...

**Comment by djbw** [comment]
I'm not sure I understand your question, but the mechanism we enable with memory is "pfn_to_page()". The inner details of how pfn_to_page() works requires understanding how Linux maps memory. In particular we take advantage of memory hotplug (via arch_add_memory()) to set up the pfn_to_page() array with vmemmap_populate().

**Comment by fengyuleidian0615** [comment]
Thanks Dan! I will revisit the memory subsystem first and come back later, close the thread for now.
