### ISSUE TITLE
json-c at least 0.14 needed but not checked for

### ISSUE THREAD

**Issue by hramrach** [pmem/ndctl#233]
[   55s] FAILED: cxl/cxl 
[   55s] cc  -o cxl/cxl cxl/cxl.p/cxl.c.o cxl/cxl.p/list.c.o cxl/cxl.p/port.c.o cxl/cxl.p/bus.c.o cxl/cxl.p/region.c.o cxl/cxl.p/memdev.c.o cxl/cxl.p/json.c.o cxl/cxl.p/filter.c.o cxl/cxl.p/event_trace.c.o cxl/cxl.p/monitor.c.o -Wl,--as-needed -Wl,--no-undefined -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g '-Wl,-rpath,$ORIGIN/lib' -Wl,-rpath-link,/home/abuild/rpmbuild/BUILD/ndctl-76/x86_64-suse-linux/cxl/lib -Wl,--start-group cxl/lib/libcxl.so.1.1.3 util/libutil.a /usr/lib64/libuuid.so /usr/lib64/libkmod.so /usr/lib64/libjson-c.so /usr/lib64/libtraceevent.so /usr/lib64/libtracefs.so -liniparser -Wl,--end-group
[   55s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cxl/cxl.p/event_trace.c.o: in function `num_to_json':
[   55s] /home/abuild/rpmbuild/BUILD/ndctl-76/x86_64-suse-linux/../cxl/event_trace.c:28: undefined reference to `json_object_new_uint64'
[   55s] /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cxl/cxl.p/event_trace.c.o: in function `cxl_event_to_json':
[   55s] /home/abuild/rpmbuild/BUILD/ndctl-76/x86_64-suse-linux/../cxl/event_trace.c:101: undefined reference to `json_object_new_uint64'

**Comment by stellarhopper** [comment]
Fixes sent: https://lore.kernel.org/linux-cxl/20230223-meson-build-fixes-v1-0-5fae3b606395@intel.com
I'll do a 76.1 with these once reviewed
