### ISSUE TITLE
Make check on OpenSuse 4.12.0-rc4-2-default

### ISSUE THREAD

**Issue by micleli** [pmem/ndctl#24]
OS:OpenSuse 4.12.0-rc4-2-default

I configure kernel as "Unit Tests", and nfit_test loaded, but still failed when make check? Is anything wrong in my environment?

[dmesg.txt](https://github.com/pmem/ndctl/files/1130521/dmesg.txt)
[lsmod.txt](https://github.com/pmem/ndctl/files/1130520/lsmod.txt)
[test-suite.txt](https://github.com/pmem/ndctl/files/1130522/test-suite.txt)

[config.txt](https://github.com/pmem/ndctl/files/1130525/config.txt)

SKIP: dsm-fail
==============

test/init: nfit_test_init: libnvdimm.ko: expected taint: O got: 
__ndctl_test_skip: explicit skip test_dsm_fail:177
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0x1c6c270 released
attempted: 1 skipped: 1
SKIP dsm-fail (exit status: 77)

SKIP: dpa-alloc
===============

test/init: nfit_test_init: libnvdimm.ko: expected taint: O got: 
__ndctl_test_skip: explicit skip test_dpa_alloc:304
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0x961270 released
attempted: 1 skipped: 1
SKIP dpa-alloc (exit status: 77)

SKIP: parent-uuid
=================

test/init: nfit_test_init: libnvdimm.ko: expected taint: O got: 
__ndctl_test_skip: explicit skip test_parent_uuid:234
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0x6e2270 released
attempted: 1 skipped: 1
SKIP parent-uuid (exit status: 77)

SKIP: multi-pmem
================

test/init: nfit_test_init: libnvdimm.ko: expected taint: O got: 
__ndctl_test_skip: explicit skip test_multi_pmem:271
nfit_test unavailable skipping tests
libndctl: ndctl_unref: context 0x2501270 released
attempted: 1 skipped: 1
SKIP multi-pmem (exit status: 77)

FAIL: create.sh
===============

+ DEV=
+ NDCTL=../ndctl/ndctl
+ BUS='-b nfit_test.0'
+ json2var='s/[{}",]//g; s/:/=/g'
+ SECTOR_SIZE=4096
+ rc=77
+ set -e
+ check_min_kver 4.5
+ local ver=4.5
++ uname -r
+ : 4.12.0-rc4-2-default+
+ '[' -n 4.5 ']'
++ echo -e '4.5\n4.12.0-rc4-2-default+'
++ sort -V
++ head -1
+ [[ 4.5 == \4\.\5 ]]
+ set -e
+ trap 'err $LINENO' ERR
+ modprobe nfit_test
+ ../ndctl/ndctl disable-region -b nfit_test.0 all
disabled 6 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.0 all
zeroed 4 nmems
+ ../ndctl/ndctl enable-region -b nfit_test.0 all
libndctl: ndctl_region_enable: region1: failed to enable
libndctl: ndctl_region_enable: region3: failed to enable
libndctl: ndctl_region_enable: region5: failed to enable
libndctl: ndctl_region_enable: region2: failed to enable
libndctl: ndctl_region_enable: region4: failed to enable
libndctl: ndctl_region_enable: region6: failed to enable
enabled 0 regions
+ rc=1
+ dev=x
++ ../ndctl/ndctl create-namespace -b nfit_test.0 -t pmem -m raw
failed to create namespace: no suitable capacity found
+ json=
++ err 52
++ echo 'test/create: failed at line 52'
test/create: failed at line 52
++ exit 1
FAIL create.sh (exit status: 1)

FAIL: clear.sh
==============

+ DEV=
+ NDCTL=../ndctl/ndctl
+ BUS='-b nfit_test.0'
+ BUS1='-b nfit_test.1'
+ json2var='s/[{}",]//g; s/:/=/g'
+ rc=77
+ set -e
+ check_min_kver 4.6
+ local ver=4.6
++ uname -r
+ : 4.12.0-rc4-2-default+
+ '[' -n 4.6 ']'
++ echo -e '4.6\n4.12.0-rc4-2-default+'
++ sort -V
++ head -1
+ [[ 4.6 == \4\.\6 ]]
+ set -e
+ trap 'err $LINENO' ERR
+ modprobe nfit_test
+ ../ndctl/ndctl disable-region -b nfit_test.0 all
disabled 6 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.0 all
zeroed 4 nmems
+ ../ndctl/ndctl enable-region -b nfit_test.0 all
libndctl: ndctl_region_enable: region1: failed to enable
libndctl: ndctl_region_enable: region3: failed to enable
libndctl: ndctl_region_enable: region5: failed to enable
libndctl: ndctl_region_enable: region2: failed to enable
libndctl: ndctl_region_enable: region4: failed to enable
libndctl: ndctl_region_enable: region6: failed to enable
enabled 0 regions
+ rc=1
+ dev=x
++ ../ndctl/ndctl create-namespace -b nfit_test.0 -t pmem -m raw
failed to create namespace: no suitable capacity found
+ json=
++ err 52
++ echo 'test/clear: failed at line 52'
test/clear: failed at line 52
++ exit 1
FAIL clear.sh (exit status: 1)

SKIP: dax-errors.sh
===================

+ DEV=
+ NDCTL=../ndctl/ndctl
+ BUS='-b nfit_test.0'
+ BUS1='-b nfit_test.1'
+ MNT=test_dax_mnt
+ FILE=image
+ json2var='s/[{}",]//g; s/:/=/g'
+ rc=77
+ check_min_kver 4.7
+ local ver=4.7
++ uname -r
+ : 4.12.0-rc4-2-default+
+ '[' -n 4.7 ']'
++ echo -e '4.7\n4.12.0-rc4-2-default+'
++ sort -V
++ head -1
+ [[ 4.7 == \4\.\7 ]]
+ set -e
+ mkdir -p test_dax_mnt
+ trap 'err $LINENO' ERR
+ modprobe nfit_test
+ ../ndctl/ndctl disable-region -b nfit_test.0 all
disabled 6 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.0 all
zeroed 4 nmems
+ ../ndctl/ndctl enable-region -b nfit_test.0 all
libndctl: ndctl_region_enable: region1: failed to enable
libndctl: ndctl_region_enable: region3: failed to enable
libndctl: ndctl_region_enable: region5: failed to enable
libndctl: ndctl_region_enable: region2: failed to enable
libndctl: ndctl_region_enable: region4: failed to enable
libndctl: ndctl_region_enable: region6: failed to enable
enabled 0 regions
+ rc=1
+ dev=x
++ ../ndctl/ndctl create-namespace -b nfit_test.0 -t pmem -m raw
failed to create namespace: no suitable capacity found
+ json=
++ err 62
++ rc=1
++ echo 'test/dax-errors: failed at line 62'
test/dax-errors: failed at line 62
++ rm -f image
++ rm -f test_dax_mnt/image
++ '[' -n '' ']'
++ rc=77
++ rmdir test_dax_mnt
++ exit 77
SKIP dax-errors.sh (exit status: 77)

FAIL: daxdev-errors.sh
======================

+ DEV=
+ NDCTL=../ndctl/ndctl
+ DAXCTL=../daxctl/daxctl
+ BUS='-b nfit_test.0'
+ BUS1='-b nfit_test.1'
+ json2var='s/[{}",]//g; s/:/=/g'
+ rc=77
+ check_min_kver 4.12
+ local ver=4.12
++ uname -r
+ : 4.12.0-rc4-2-default+
+ '[' -n 4.12 ']'
++ echo -e '4.12\n4.12.0-rc4-2-default+'
++ sort -V
++ head -1
+ [[ 4.12 == \4\.\1\2 ]]
+ set -e
+ trap 'err $LINENO' ERR
+ modprobe nfit_test
+ ../ndctl/ndctl disable-region -b nfit_test.0 all
disabled 6 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.0 all
zeroed 4 nmems
+ ../ndctl/ndctl enable-region -b nfit_test.0 all
libndctl: ndctl_region_enable: region1: failed to enable
libndctl: ndctl_region_enable: region3: failed to enable
libndctl: ndctl_region_enable: region5: failed to enable
libndctl: ndctl_region_enable: region2: failed to enable
libndctl: ndctl_region_enable: region4: failed to enable
libndctl: ndctl_region_enable: region6: failed to enable
enabled 0 regions
+ query='. | sort_by(.available_size) | reverse | .[0].dev'
++ ../ndctl/ndctl list -b nfit_test.0 -t pmem -Ri
++ jq -r '. | sort_by(.available_size) | reverse | .[0].dev'
./daxdev-errors.sh: line 49: jq: command not found
+ region=
++ err 49
++ rc=1
++ echo 'test/daxdev-errors: failed at line 49'
test/daxdev-errors: failed at line 49
++ exit 1
FAIL daxdev-errors.sh (exit status: 1)

SKIP: btt-check.sh
==================

kernel 4.12.0-rc4-2-default+ may not support badblocks clearing on pmem via btt
SKIP btt-check.sh (exit status: 77)

SKIP: label-compat.sh
=====================

+ NDCTL=../ndctl/ndctl
+ BUS='-b nfit_test.0'
+ BUS1='-b nfit_test.1'
+ rc=77
+ set -e
+ check_min_kver 4.11
+ local ver=4.11
++ uname -r
+ : 4.12.0-rc4-2-default+
+ '[' -n 4.11 ']'
++ echo -e '4.11\n4.12.0-rc4-2-default+'
++ sort -V
++ head -1
+ [[ 4.11 == \4\.\1\1 ]]
+ set -e
+ trap 'err $LINENO' ERR
+ modprobe nfit_test
+ ../ndctl/ndctl disable-region -b nfit_test.0 all
disabled 6 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.0 all
zeroed 4 nmems
+ query='. | sort_by(.available_size) | reverse | .[0].dev'
++ ../ndctl/ndctl list -b nfit_test.0 -t pmem -Ri
++ jq -r '. | sort_by(.available_size) | reverse | .[0].dev'
./label-compat.sh: line 47: jq: command not found
+ region=
++ err 47
++ echo 'test/label-compat.sh: failed at line 47'
test/label-compat.sh: failed at line 47
++ exit 77
SKIP label-compat.sh (exit status: 77)

FAIL: blk-exhaust.sh
====================

+ NDCTL=../ndctl/ndctl
+ BUS='-b nfit_test.0'
+ BUS1='-b nfit_test.1'
+ rc=77
+ set -e
+ check_min_kver 4.11
+ local ver=4.11
++ uname -r
+ : 4.12.0-rc4-2-default+
+ '[' -n 4.11 ']'
++ echo -e '4.11\n4.12.0-rc4-2-default+'
++ sort -V
++ head -1
+ [[ 4.11 == \4\.\1\1 ]]
+ set -e
+ trap 'err $LINENO' ERR
+ modprobe nfit_test
+ ../ndctl/ndctl disable-region -b nfit_test.0 all
disabled 6 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.0 all
zeroed 4 nmems
+ ../ndctl/ndctl enable-region -b nfit_test.0 all
libndctl: ndctl_region_enable: region1: failed to enable
libndctl: ndctl_region_enable: region3: failed to enable
libndctl: ndctl_region_enable: region5: failed to enable
libndctl: ndctl_region_enable: region2: failed to enable
libndctl: ndctl_region_enable: region4: failed to enable
libndctl: ndctl_region_enable: region6: failed to enable
enabled 0 regions
+ rc=1
+ ../ndctl/ndctl create-namespace -b nfit_test.0 -t pmem
failed to create namespace: no suitable capacity found
++ err 49
++ echo 'test/label-compat.sh: failed at line 49'
test/label-compat.sh: failed at line 49
++ exit 1
FAIL blk-exhaust.sh (exit status: 1)

**Comment by djbw** [comment]
Yes, the test version of the modules are not installed correctly. You can see that the unit tests are finding the production version of the libnvdimm.ko module with this error message "test/init: nfit_test_init: libnvdimm.ko: expected taint: O got:"
