### ISSUE TITLE
RHEL 8: cxl-cli not found (base+elrepo+epel)

### ISSUE THREAD

**Issue by alexisfrjp** [pmem/ndctl#245]
```
$ sudo dnf install cxl-cli
Last metadata expiration check: 3:50:30 ago on Wed 10 May 2023 06:06:00 PM JST.
No match for argument: cxl-cli
Error: Unable to find a match: cxl-cli
```

* https://docs.pmem.io/ndctl-user-guide/installing-ndctl/installing-the-cxl-cli-package-on-linux

> The cxl-cli package is available on CentOS, RHEL, RHEL for SAP HANA 7.0 or later. 

It isn't.

I also tried to compile it on RHEL 8.7:

> meson.build:148:2: ERROR: Dependency "libtracefs" not found, tried pkgconfig and cmake

libtracefs doesn't exist either

**Comment by djbw** [comment]
You can find a package built for CentOS Stream 8 here:

https://copr.fedorainfracloud.org/coprs/djbw/ndctl/

**Comment by alexisfrjp** [comment]
Thank you, I had the nmctl-71, using your repo allowed me to install the latest one.
