### ISSUE TITLE
Failed to create namespace with DAX mode

### ISSUE THREAD

**Issue by yassineba** [pmem/ndctl#25]
I would like to experiment Device DAX, I emulate two persistent memory devices with 16G each one in my system using OS: RH 7.4.
When I use ndctl tool to configure dax mode : 
`#ndctl create-namespace -m dax -e namespace0.0 -f`
I get this error : 
```
libndctl: ndctl_dax_enable: dax0.0: failed to enable
  Error: namespace0.0: failed to enable

failed to reconfigure namespace
```

Can you please confirm to me if this is the correct step : to configure dax mode and to experiment Device DAX in my system ? 

Thanks !

**Comment by yassineba** [comment]
I add the syslog messages according to this error : 

```
[ 1361.970085] dax_pmem dax0.0: alignment must be PAGE_SIZE
[ 1362.060194] dax_pmem: probe of dax0.0 failed with error -12
```

**Comment by djbw** [comment]
Yes, that's the correct way to enable device-dax mode. Which kernel version and ndctl version are you running? Send the output of "uname -r" and "ndctl --version". I'll otherwise fire up a RH 7.4 machine and take a look.

**Comment by yassineba** [comment]
Thank you ! 
The kernel version under RH7.4 is :
```
[root@localhost yassine]# uname -r
3.10.0-679.el7.x86_64
```
The ndctl version I use  : 
```
[root@localhost yassine]# ndctl --version
58.2+
```

**Comment by djbw** [comment]
Ok, first revert the namespace back to 'raw' mode:

```
    ndctl destroy-namespace namespace0.0
    ndctl enable-namespace namespace0.0
```
...and then set dax mode, but be sure to specify the alignment as 4K:

```
    ndctl create-namespace -m dax -e namespace0.0 -a 4k -f
```

This is caused by the fact that device-dax in 3.10.0-679.el7.x86_64 only supports 4K mappings, not the 2MB mappings that ndctl expects by default.

**Comment by yassineba** [comment]
It works ! thank you
