### ISSUE TITLE
Skip sector-mode test in make check 

### ISSUE THREAD

**Issue by ironhide888** [pmem/ndctl#26]
My linux kernel is 4.14.0-rc1-mytest. I have an issue as following.

~/ndctl$ sudo make check
  GEN      version.m4
make --no-print-directory check-recursive
  GEN      version.m4
Making check in .
  GEN      version.m4
Making check in daxctl/lib
make[2]: Nothing to be done for 'check'.
Making check in ndctl/lib
make --no-print-directory check-am
make[3]: Nothing to be done for 'check-am'.
Making check in ndctl
make[2]: Nothing to be done for 'check'.
Making check in daxctl
make[2]: Nothing to be done for 'check'.
Making check in Documentation/ndctl
make[2]: Nothing to be done for 'check'.
Making check in Documentation/daxctl
make[2]: Nothing to be done for 'check'.
Making check in test
make --no-print-directory libndctl dsm-fail dpa-alloc parent-uuid multi-pmem dax-errors daxdev-errors 
make[3]: 'libndctl' is up to date.
make[3]: 'dsm-fail' is up to date.
make[3]: 'dpa-alloc' is up to date.
make[3]: 'parent-uuid' is up to date.
make[3]: 'multi-pmem' is up to date.
make[3]: 'dax-errors' is up to date.
make[3]: 'daxdev-errors' is up to date.
make --no-print-directory check-TESTS
PASS: libndctl
PASS: dsm-fail
PASS: dpa-alloc
PASS: parent-uuid
PASS: multi-pmem
PASS: create.sh
PASS: clear.sh
PASS: dax-errors.sh
PASS: daxdev-errors.sh
PASS: multi-dax.sh
PASS: btt-check.sh
PASS: label-compat.sh
PASS: blk-exhaust.sh
SKIP: sector-mode.sh
============================================================================
Testsuite summary for ndctl 58.2
============================================================================
# TOTAL: 14
# PASS:  13
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

test/test-suite.log
=====================================
   ndctl 58.2: test/test-suite.log
=====================================

# TOTAL: 14
# PASS:  13
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

SKIP: sector-mode.sh
====================

+ NDCTL=../ndctl/ndctl
+ BUS='-b nfit_test.0'
+ BUS1='-b nfit_test.1'
+ TEST=./sector-mode.sh
+ rc=77
+ set -e
+ trap 'err $LINENO' ERR
+ modprobe nfit_test
+ ../ndctl/ndctl disable-region -b nfit_test.0 all
disabled 6 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.0 all
zeroed 4 nmems
+ ../ndctl/ndctl enable-region -b nfit_test.0 all
enabled 6 regions
+ ../ndctl/ndctl disable-region -b nfit_test.1 all
disabled 2 regions
+ ../ndctl/ndctl zero-labels -b nfit_test.1 all
zeroed 2 nmems
+ echo 'DIMMs on -b nfit_test.1 support labels, skip...'
DIMMs on -b nfit_test.1 support labels, skip...
+ ../ndctl/ndctl enable-region -b nfit_test.1 all
enabled 2 regions
+ false
++ err 38
++ echo './sector-mode.sh: failed at line 38'
./sector-mode.sh: failed at line 38
++ exit 77
SKIP sector-mode.sh (exit status: 77)

Is anything i miss or un-install in my system?

**Comment by djbw** [comment]
You need at least kernel version 4.14-rc2 with this change:

5e75fe392755 tools/testing/nvdimm: disable labels for nfit_test.1

**Comment by ironhide888** [comment]
Is ndctl function work when i install ndctl with the case? I mean sector-mode is skipped, but i still install ndctl in my system.

**Comment by djbw** [comment]
Yes, it will work fine even if that unit test is skipped.

**Comment by ironhide888** [comment]
My system has one real NVDIMM, and i installed ndctl utility already. Nothing is shown while ndctl list is issued.
But if i execute the following commands.
~/ndctl$ sudo modprobe nfit_test
~/ndctl$ ndctl list
[
  {
    "dev":"namespace7.0",
    "mode":"raw",
    "size":4194304,
    "blockdev":"pmem7"
  },
  {
    "dev":"namespace6.0",
    "mode":"raw",
    "size":33554432,
    "blockdev":"pmem6",
    "badblock_count":8
  }
]
The two devices "pmem6" and "pmem7" are shown after ndctl list. 
Are pmem6 and pmem7 emulate for testing? Do they not map to real NVDIMM?
How can i use one namespace to indicate NVDIMM?

**Comment by djbw** [comment]
Does your system provide an NFIT. See the output of "ndctl list -B" and look for "ACPI.NFIT". If that's not there your BIOS needs an update.

**Comment by ironhide888** [comment]
I can find NFIT in /sys/firmware/acpi/tables/. But nothing is shown when executing ndctl list -B.
My BIOS is up to date. I will contact BIOS vendor for the issue.
