### ISSUE TITLE
ndctl list -X returns different output than specified in documentation

### ISSUE THREAD

**Issue by kasiawasiuta** [pmem/ndctl#27]
repro:
`ndctl list -X`

>  {
>     "dev":"namespace0.0",
>     "mode":"dax",
>     "size":1054867456,
>     "uuid":"033c78b2-39f4-428d-85d1-88941905f848",
>     "daxregion":{
>       "id":0,
>       "devices":[
>         {
>           "chardev":"dax0.0",
>           "size":1035993088
>         }
>       ]
>     },
>     "numa_node":0
>   }

There is no alignment or size specified in daxregion (listed in documentation), and sizes differ.
ndctl version: 58.2

**Comment by djbw** [comment]
What kernel version are you running? Those attributes may not be available.

**Comment by kasiawasiuta** [comment]
4.4.59-92.17-default

**Comment by djbw** [comment]
Ok, I assume does not have this commit backported:

    d7fe1a67f658 dax: add region 'id', 'size', and 'align' attributes

It was added to the upstream kernel in v4.10.

**Comment by kasiawasiuta** [comment]
Ok, that must be it, thanks for your help!
