### ISSUE TITLE
failed make check

### ISSUE THREAD

**Issue by zhuguoliang** [pmem/ndctl#3]
Hi pmem community for ndctl 

I am playing with kernel 4.4.0 with the necessary DAX configuration enabled following the guide on https://nvdimm.wiki.kernel.org/.

I sucessfully mounted pmem dax.

 df -h |fgrep /mnt/mem
/dev/pmem0       16G   44M   15G   1% /mnt/mem

then  I tred make/make check in ndctl home.

I got the following error and I don't understand if it is because of configuration or because of anything else.

by executing lsmod |grep nfit_test I got the following 

> nfit_test              24576  4
> nfit                   32768  1 nfit_test
> nfit_test_iomap        16384  1 nfit_test
> libnvdimm              98304  5 nfit,nd_e820,nd_pmem,nfit_test,nd_btt
> 

However, here is my make check result in test-suit.log
```
FAIL: test/libndctl
===================

libkmod: DEBUG ../libkmod/libkmod.c:392 kmod_pool_get_module: get module name='nfit_test' found=(nil)
libkmod: DEBUG ../libkmod/libkmod.c:400 kmod_pool_add_module: add 0x7e9020 key='nfit_test'
check_set_config_data: dimm: 0 read2 data miscompare: 0
check_set_config_data: dimm: 0x1 read2 data miscompare: 0
check_set_config_data: dimm: 0x100 read2 data miscompare: 0
check_set_config_data: dimm: 0x101 read2 data miscompare: 0
libndctl: ndctl_region_enable: region7: failed to enable
libndctl: ndctl_region_enable: region6: failed to enable
libndctl: ndctl_region_enable: region5: failed to enable
libndctl: ndctl_region_enable: region4: failed to enable
libndctl: ndctl_region_enable: region3: failed to enable
libndctl: ndctl_btt_enable: btt1.0: failed to enable
btt1.0: expected btt enable success, region1 read-write
namespace1.0: failed to create btt
namespace1.0: failed to configure namespace
ndctl-test0 failed: -6
libkmod: ERROR ../libkmod/libkmod-module.c:769 kmod_module_remove_module: could not remove 'nfit_test': Resource temporarily unavailable
libndctl: ndctl_unref: context 0x7e32e0 released
zhuguoliang think kver is 263168

FAIL: test/dpa-alloc
====================

libndctl: ndctl_region_enable: region3: failed to enable
failed to find a usable BLK region
libndctl: ndctl_unref: context 0xf7c2e0 released
zhuguoliang think kver is 263168

FAIL: test/parent-uuid
======================

failed to create block namespace
libkmod: ERROR ../libkmod/libkmod-module.c:769 kmod_module_remove_module: could not remove 'nfit_test': Resource temporarily unavailable
libndctl: ndctl_unref: context 0x1f8b2e0 released
zhuguoliang think kver is 263168

FAIL: test/create.sh
```
====================

**Comment by djbw** [comment]
The unit tests are developed to exercise the latest features in the kernel.  While kernel changes will never break existing ndctl binaries, there is no guarantee that the unit tests from newer ndctl's will run against older kernels.

In this case please try running against the latest 4.5 kernel rather than 4.4.

**Comment by zhuguoliang** [comment]
Thanks Mr Williams!
However I think maybe it has something to do with the LINUX_VERSION_CODE? 
I happen to find that the version got by libndctl is 3.12.13 which is my orginal system linux version for Ubuntu 14.04. I compiled and run 4.4.0 but libndctl also thinks the version is 3.12.13. 
Why is this?
I manually changed the version in file test/core.c but I think there must be something wrong with the configuration process of libndctl on my system.

**Comment by djbw** [comment]
It gets the linux version code from /usr/include/linux/version.h.  You need to do "make INSTALL_HDR_PATH=/usr headers_install" in your kernel source directory to use the headers from that kernel.

**Comment by zhuguoliang** [comment]
Wow. Thanks!

**Comment by zhuguoliang** [comment]
Hi Mr. Williams, I've tried your suggestion of linux kernel 4.5-rc2+ 
However, I also get the following result:
`libkmod: DEBUG ../libkmod/libkmod.c:392 kmod_pool_get_module: get module name='nfit_test' found=(nil)
libkmod: DEBUG ../libkmod/libkmod.c:400 kmod_pool_add_module: add 0x1d27030 key='nfit_test'
check_set_config_data: dimm: 0 read2 data miscompare: 0
check_set_config_data: dimm: 0x1 read2 data miscompare: 0
check_set_config_data: dimm: 0x100 read2 data miscompare: 0
check_set_config_data: dimm: 0x101 read2 data miscompare: 0
libndctl: ndctl_region_enable: region7: failed to enable
libndctl: ndctl_region_enable: region6: failed to enable
libndctl: ndctl_region_enable: region5: failed to enable
libndctl: ndctl_region_enable: region4: failed to enable
libndctl: ndctl_region_enable: region3: failed to enable
libndctl: ndctl_btt_enable: btt1.0: failed to enable
btt1.0: expected btt enable success, region1 read-write
namespace1.0: failed to create btt
namespace1.0: failed to configure namespace
ndctl-test0 failed: -6
libkmod: ERROR ../libkmod/libkmod-module.c:769 kmod_module_remove_module: could not remove 'nfit_test': Resource temporarily unavailable
libndctl: ndctl_unref: context 0x1d212e0 released
test-libndctl: FAIL`

by lsmod |grep nfit  I get:
`nfit_test              24576  4
nfit                   32768  1 nfit_test
nfit_test_iomap        16384  1 nfit_test
libnvdimm             102400  5 nfit,nd_e820,nd_pmem,nfit_test,nd_btt`

What should I do to fix this?

**Comment by djbw** [comment]
There's known bugs in the DAX implementation in 4.5-rc2 that are fixed in 4.5-rc7, but even there I was able to successfully run "make TESTS=test/libndctl check".  You can get more debug with the following kernel command line options:

libnvdimm.dyndbg nfit.dyndbg nd_pmem.dyndbg

Here is my kernel configuration:
[config.txt](https://github.com/pmem/ndctl/files/165692/config.txt)

**Comment by djbw** [comment]
So I just hit a problem similar to this and it came down to the fact that I had changed the module install order.  In the failing case modinfo returns:

# modinfo libnvdimm
filename:       /lib/modules/4.5.0-rc7-next-20160310/kernel/drivers/nvdimm/libnvdimm.ko

...in the passing case it returns:

# modinfo libnvdimm
filename:       /lib/modules/4.5.0-rc7-next-20160310/extra/libnvdimm.ko

So make sure you are doing module install in the following order.

sudo make M=tools/testing/nvdimm/ modules_install
sudo make modules_install

...this makes sure the extra/ directory is populated before the full modules_install runs its dependency checks.

**Comment by yide1728** [comment]
Hello Mr. Williams
I'm using 4.7.0-rc4+, seems also met this problem, could you help check it? thanks.
I have attached the config and dmesg log.

[root@storageqe-55 ndctl]# modinfo libnvdimm
filename:       /lib/modules/4.7.0-rc4+/extra/libnvdimm.ko
author:         Intel Corporation
license:        GPL v2
alias:          nd:t1*
alias:          nd:t3*
alias:          nd:t2*
srcversion:     AA9F7D23DAFC6B8B8DE4BFE
depends:        nfit_test_iomap
vermagic:       4.7.0-rc4+ SMP mod_unload modversions 

[root@localhost ndctl]# cat test/libndctl.log 
check_set_config_data: dimm: 0 read2 data miscompare: 0
check_ars_status: record[0].addr: 0x800
check_ars_status: record[0].length: 0x1000
check_set_config_data: dimm: 0x1 read2 data miscompare: 0
check_ars_status: record[0].addr: 0x800
check_ars_status: record[0].length: 0x1000
check_set_config_data: dimm: 0x100 read2 data miscompare: 0
check_ars_status: record[0].addr: 0x800
check_ars_status: record[0].length: 0x1000
check_set_config_data: dimm: 0x101 read2 data miscompare: 0
check_ars_status: record[0].addr: 0x800
check_ars_status: record[0].length: 0x1000
check_dax_create: 4
__check_dax_create: dax5.0 align: 1
libdaxctl: daxctl_region_unref: region5 released
__check_dax_create: dax5.1 align: 1073741824
libndctl: ndctl_dax_enable: dax5.1: failed to enable
__check_dax_create: dax5.1 align: 4096
libdaxctl: daxctl_region_unref: region5 released
__check_dax_create: dax5.0 align: 2097152
libndctl: ndctl_dax_enable: dax5.0: failed to enable
dax5.0: expected dax enable success, region5 read-write
namespace5.0: failed to create dax
namespace5.0: failed to configure namespace
ndctl-test0 failed: -6
libkmod: kmod_module_remove_module: could not remove 'nfit_test': Resource temporarily unavailable
libdaxctl: daxctl_unref: context 0x1cdd0d0 released
libndctl: ndctl_unref: context 0x1cdd410 released

[config.txt](https://github.com/pmem/ndctl/files/330010/config.txt)

[dmesg.txt](https://github.com/pmem/ndctl/files/330012/dmesg.txt)

**Comment by djbw** [comment]
See the explanation for this failure here:
https://lists.01.org/pipermail/linux-nvdimm/2016-June/006212.html
