### ISSUE TITLE
v59.2 - Can't create dax device on Ubuntu 16.04.1 LTS with kernel 4.9.4

### ISSUE THREAD

**Issue by mramotowski** [pmem/ndctl#34]
Can't create dax device on Ubuntu 16.04.1 LTS with kernel 4.9.4

```
user@user:~$ ndctl --version
58.4
user@user:~$ sudo ndctl create-namespace -e namespace1.0 -f -m dax -v
{
  "dev":"namespace1.0",
  "mode":"dax",
  "size":"2014.00 MiB (2111.83 MB)",
  "uuid":"d4dce333-5823-41d9-81fc-6f6a4900932f",
  "daxregion":{
    "id":1,
    "devices":[
      {   
        "chardev":"dax1.0",
        "size":"2014.00 MiB (2111.83 MB)"
      }   
    ]   
  },  
  "numa_node":0
}
user@user:~$ ndctl --version
59.2.1.gfd0f527
user@user:~$ sudo ndctl create-namespace -e namespace1.0 -f -m dax -v
sudo: unable to resolve host 71-114: Connection timed out 
validate_namespace_options:569: region1: falling back to a 4K alignment
libndctl: ndctl_dax_enable: dax1.0: failed to enable
  Error: namespace1.0: failed to enable

failed to reconfigure namespace: No such device or address

```
After using create-namespace with ndctl v59.2 namespace is disapring. Works fine with v58.4

**Comment by djbw** [comment]
Thanks for the report, I'll bisect this to find out where it broke.

**Comment by djbw** [comment]
The output from dmesg immediately after boot would also be useful.

**Comment by mrharrylp** [comment]
I checked this issue on kernel 4.13 and none of tested ndctl versions (v57.1, v58.4, v59.2) worked properly (see log 4.13+ndctl59.2) - is that a separate issue...?

I switched back to 4.9.4 and gathered data you asked for (log 4.9.4+ndctl59.2)

I also checked kernel 4.15 with all of aforementioned ndctl versions and they all worked fine

[4.13+ndctl59.2.log](https://github.com/pmem/ndctl/files/1770822/4.13.ndctl59.2.log)
[4.9.4+ndctl59.2.log](https://github.com/pmem/ndctl/files/1770823/4.9.4.ndctl59.2.log)

**Comment by djbw** [comment]
Fix is [here](https://patchwork.kernel.org/patch/10256267/)
