### ISSUE TITLE
CentOS 7 make Fail

### ISSUE THREAD

**Issue by vikrammm** [pmem/ndctl#36]
[root@localhost ndctl-master]# make
  GEN      version.m4
make --no-print-directory all-recursive
  GEN      version.m4
Making all in .
  GEN      version.m4
  CC       ccan/str/str.o
  CC       ccan/str/debug.o
  CC       ccan/list/list.o
  AR       libccan.a
  CC       util/parse-options.o
  CC       util/usage.o
  CC       util/size.o
  CC       util/main.o
  CC       util/help.o
  CC       util/strbuf.o
  CC       util/wrapper.o
  CC       util/filter.o
  CC       util/bitmap.o
  AR       libutil.a
  GEN      rhel/ndctl.spec
  GEN      sles/ndctl.spec
Making all in daxctl/lib
  CC       ../../util/sysfs.lo
  CC       ../../util/log.lo
  CC       libdaxctl.lo
  CCLD     libdaxctl.la
  GEN      libdaxctl.pc
Making all in ndctl/lib
  CC       dimm.lo
  CC       inject.lo
  CC       nfit.lo
  CC       smart.lo
  CC       intel.lo
  CC       hpe1.lo
  CC       msft.lo
  CC       ars.lo
  CC       firmware.lo
  CC       libndctl.lo
  CCLD     libndctl.la
  GEN      libndctl.pc
Making all in ndctl
  CC       ndctl.o
  CC       create-nfit.o
  CC       namespace.o
  CC       check.o
  CC       region.o
  CC       dimm.o
  CC       ../util/log.o
  CC       list.o
  CC       test.o
  CC       ../util/json.o
  CC       util/json-smart.o
  CC       inject-error.o
  CC       update.o
  CC       inject-smart.o
  CCLD     ndctl
Making all in daxctl
  CC       daxctl.o
  CC       list.o
  CC       ../util/json.o
  CCLD     daxctl
Making all in Documentation/ndctl
  GEN      ndctl.xml
  GEN      ndctl.1
xmlto: /home/sql-linux_cr/Downloads/CR/ndctl-master/Documentation/ndctl/ndctl.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/home/sql-linux_cr/Downloads/CR/ndctl-master/Documentation/ndctl/ndctl.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
Document /home/sql-linux_cr/Downloads/CR/ndctl-master/Documentation/ndctl/ndctl.xml does not validate
make[2]: *** [ndctl.1] Error 13
rm ndctl.xml
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Kernel: 3.10.0-693

Not sure why it fails. There is active internet, able to install packages through yum.

**Comment by stellarhopper** [comment]
Sounds like this may have been due to an unreachable network resource. Is this still a problem?

**Comment by vikrammm** [comment]
No, you can close this Issue. I found an rpm for centos for NDCTL. thanks
