### ISSUE TITLE
sth about libndctl.so and libndctl.h

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#38]
My purpose is to use the interface provided by ndctl to do ARS in the system which has the nvdimm running.

after compiling the ndctl, i got the libndctl.so and libdaxctl.so.

Is the libndctl.so and libndctl.h enough to help me realize my function（ARS）？

@djbw

**Comment by djbw** [comment]
Yes, however, if you install the ndctl-devel package, you should just be able to link your application to libndctl with:

gcc -lndctl

That said, there are some recent patches implementing ARS start and ARS wait for completion functionality. Perhaps those already have the functionality you need?

https://lists.01.org/pipermail/linux-nvdimm/2018-April/015125.html

**Comment by insanecoderr** [comment]
@djbw 
Thanks，but how can i get the patch?  i cant find it even in master branch.

**Comment by djbw** [comment]
You can find this functionality on the 'pending' branch: https://github.com/pmem/ndctl/tree/pending it is targeting the next release (v60).

**Comment by insanecoderr** [comment]
@djbw 
Thanks a lot ,i found it!

Moreover,the ndctl_start_scrub() api does not specify the start addr and the scrub length, i hope that i can initiate the scrub within a desired range. any suggestions on it？

**Comment by djbw** [comment]
What's the use case for scrubbing a specific range vs global? The kernel will perform a global scrub at boot, and will dynamically add addresses to the badblocks tracking as they are discovered at run time. Userspace can trigger more global flushes, but userspace shouldn't know or care about scrubbing specific address ranges.

That said, there are these apis:

ndctl_bus_cmd_new_ars_cap
ndctl_bus_cmd_new_ars_start
ndctl_bus_cmd_new_ars_status

...but be warned that the kernel will not see the results of those operations. I.e. those scrub results will only be consumed by userspace and any badblocks found will not be tracked by the kernel.

**Comment by djbw** [comment]
You should use "ndctl list --media-errors". That will report the results of the global ARS scrub performed by the kernel. It is not efficient for individual applications to redo this work.

**Comment by insanecoderr** [comment]
@djbw 

forget the  message "3.about the block device", i have some misunderstanding on it.

by the way, how do i get the input of ndctl_bus_cmd_new_ars_cap "address" and "len",can i get it in this way:
[root@localhost z00392707]# cat /proc/iomem|grep -i namespace
3040000000-6f3fffffff : namespace2.0
?

**Comment by insanecoderr** [comment]
@djbw 

i performed ndctl list --media-errors,since there may be no error in the system, i dont get the err address. Will the cmd provide the err address if available? because application wants to know the address

[root@localhost z00392707]# ndctl list --media-errors
{
  "dev":"namespace2.0",
  "mode":"raw",
  "size":270582939648,
  "uuid":"d9ad1df4-a198-4a39-b20a-95fc8fbc4d94",
  "blockdev":"pmem2",
  "numa_node":0
}

**Comment by djbw** [comment]
Yes, and as you can see from this sample output it will translate the absolute error address to a namespace relative offset:

{
  "dev":"namespace7.0",
  "mode":"raw",
  "size":33554432,
  "blockdev":"pmem7",
  "badblock_count":17,
  "badblocks":[
    {
      "offset":4,
      "length":1
    },
    {
      "offset":32768,
      "length":8 
    },
    {
      "offset":65528,
      "length":8
    }
  ]
}

**Comment by djbw** [comment]
Yes, the easiest way to get that is to list the media errors at the region level:

    ndctl list -RM

...and then add the base physical  address of the region from /sys/bus/nd/devices/regionX/resource.

**Comment by insanecoderr** [comment]
@djbw 
Thanks,

by the way,i found that apis uses dbg() to log information.how to find the log?i cannot find logs the interfaces produced while some err happens.

I've searched the Makefile but found nothing related to the "ENABLE_LOGGING" or "ENABLE_DEBUG".

**Comment by djbw** [comment]
You need to have built ndctl with '--enable-logging' and '--enable-debug' options specified to the 'configure' script.

**Comment by insanecoderr** [comment]
@djbw 
Thanks! i have enabled it. But where is the log and debug message it produces?

**Comment by djbw** [comment]
The log messages go to stderr by default, but only if you have the expected log level set. See calls to ndctl_set_log_priority() as examples, i.e. ndctl_set_log_priority(ctx, LOG_DEBUG) to turn on all messages.
