### ISSUE TITLE
fail to create devdax namespace

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#39]
I tried to create devdax mode namespace,However it fails.Steps are as below:

[root@localhost z00392707]# ndctl list -R
{
  "dev":"region2",
  "size":270582939648,
  "available_size":270582939648,
  "type":"pmem",
  "iset_id":4001977599667278416
}
[root@localhost z00392707]# ndctl create-namespace --verbose -r region2 --mode=devdax
libndctl: ndctl_dax_enable: dax2.0: failed to enable
  Error: namespace2.0: failed to enable

failed to create namespace: No such device or address

@djbw could u help me with it?

@djbw addtionally the version of ndctl:
[root@localhost z00392707]# ndctl --version
59.1+

**Comment by djbw** [comment]
What kernel version and what ndctl version?

**Comment by insanecoderr** [comment]
@djbw 

[root@localhost z00392707]# uname -r
4.14.17

**Comment by chenyoumin1993** [comment]
I've tried to add params "--align=2M", and it works!

**Comment by insanecoderr** [comment]
@chenyoumin1993 thanks for you suggestion but it doesnt work for me.

@djbw here is the debug mesg:
[root@localhost ~]# ndctl create-namespace --verbose -f -e namespace2.0 --mode=dax --align=2M
libndctl: __sysfs_device_parse: base: /sys/class/nd dev: ndctl
libndctl: __sysfs_read_attr: failed to open /sys/class/nd/ndctl0/device/nfit/dsm_mask: No such file or directory
libndctl: __sysfs_device_parse: ndctl0: processed
libndctl: __sysfs_device_parse: base: /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0 dev: region
libndctl: to_module: alias: nd:t3 module: libnvdimm
libndctl: __sysfs_device_parse: region0: processed
libndctl: to_module: alias: nd:t3 module: libnvdimm
libndctl: __sysfs_device_parse: region1: processed
libndctl: to_module: alias: nd:t2 module: libnvdimm
libndctl: __sysfs_device_parse: region2: processed
libndctl: __sysfs_device_parse: base: /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2 dev: namespace2.
libndctl: __sysfs_read_attr: failed to open /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/namespace2.0/holder_class: No such file or directory
libndctl: to_module: alias: nd:t4 module: nd_pmem
libndctl: __sysfs_device_parse: namespace2.0: processed
libndctl: __sysfs_device_parse: base: /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2 dev: pfn2.
libndctl: to_module: alias: nd:t4 module: nd_pmem
libndctl: __sysfs_read_attr: failed to read /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/pfn2.0/resource: No such device or address
libndctl: __sysfs_read_attr: failed to read /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/pfn2.0/size: No such device or address
libndctl: __sysfs_device_parse: pfn2.0: processed
libndctl: __sysfs_device_parse: base: /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2 dev: dax2.
libndctl: to_module: failed to find module for alias: nd:t7 0 list: empty
libndctl: __sysfs_read_attr: failed to read /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/dax2.0/resource: No such device or address
libndctl: __sysfs_read_attr: failed to read /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/dax2.0/size: No such device or address
libndctl: __sysfs_device_parse: dax2.0: processed
libndctl: __sysfs_device_parse: base: /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2 dev: btt2.
libndctl: to_module: alias: nd:t4 module: nd_pmem
libndctl: parse_lbasize_supported: btt2.0: 512 520 528 4096 4104 4160 4224
libndctl: __sysfs_read_attr: failed to open /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/btt2.0/size: No such file or directory
libndctl: __sysfs_device_parse: btt2.0: processed
libndctl: ndctl_namespace_disable: namespace2.0: disabled
libndctl: write_attr: failed to open /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/namespace2.0/holder_class: No such file or directory
libndctl: ndctl_namespace_delete: namespace2.0: nstype: 4 not deletable
libndctl: __sysfs_device_parse: base: /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0 dev: nmem
libndctl: to_module: alias: nd:t1 module: libnvdimm
libndctl: __sysfs_read_attr: failed to open /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/nmem0/flags: No such file or directory
libndctl: parse_nfit_mem_flags: nmem0:
libndctl: __sysfs_device_parse: nmem0: processed
libndctl: to_module: alias: nd:t1 module: libnvdimm
libndctl: __sysfs_read_attr: failed to open /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/nmem1/flags: No such file or directory
libndctl: parse_nfit_mem_flags: nmem1:
libndctl: __sysfs_device_parse: nmem1: processed
libndctl: ndctl_region_disable: region2: disabled
ndctl_cmd_submit:/dev/nmem1
libndctl: do_cmd: bus: 0 dimm: 0x101 cmd: get_size status: 0 fw: 0 (success)
libndctl: do_cmd: bus: 0 dimm: 0x101 cmd: get_data total: 131072 max_xfer: 65504 status: 0 fw: 0 (success)
libndctl: do_cmd: bus: 0 dimm: 0x101 cmd: set_data total: 131072 max_xfer: 65504 status: 0 fw: 0 (success)
libndctl: do_cmd: bus: 0 dimm: 0x101 cmd: set_data total: 131072 max_xfer: 65504 status: 0 fw: 0 (success)
libndctl: ndctl_dimm_disable: nmem1: disabled
libndctl: ndctl_dimm_enable: nmem1: enabled
libndctl: do_cmd: bus: 0 dimm: 0x1 cmd: get_size status: 0 fw: 0 (success)
libndctl: do_cmd: bus: 0 dimm: 0x1 cmd: get_data total: 131072 max_xfer: 65504 status: 0 fw: 0 (success)
ndctl_cmd_submit:/dev/nmem0
total_xfer non-zero:rc:0
total_xfer non-zero:rc:0
total_xfer non-zero:rc:0
libndctl: do_cmd: bus: 0 dimm: 0x1 cmd: set_data total: 131072 max_xfer: 65504 status: 0 fw: 0 (success)
do_cmd output rc:0
in out branch
ndctl_cmd_submit:/dev/nmem0
libndctl: do_cmd: bus: 0 dimm: 0x1 cmd: set_data total: 131072 max_xfer: 65504 status: 0 fw: 0 (success)
libndctl: ndctl_dimm_disable: nmem0: disabled
libndctl: ndctl_dimm_enable: nmem0: enabled
libndctl: ndctl_bus_wait_probe: waited 4 milliseconds for bus0...
libndctl: ndctl_region_enable: region2: enabled
enable_labels:943: region2: failed to initialize labels
libndctl: __sysfs_device_parse: base: /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2 dev: namespace2.
libndctl: __sysfs_read_attr: failed to open /sys/devices/LNXSYSTM:00/device:00/ACPI0012:00/ndbus0/region2/namespace2.0/holder_class: No such file or directory
libndctl: to_module: alias: nd:t4 module: nd_pmem
libndctl: __sysfs_device_parse: namespace2.0: processed
namespace_reconfig:975: region2: no idle namespace seed
failed to reconfigure namespace: No such device
[root@localhost ~]#

**Comment by sscargal** [comment]
Q) What are you using as the non-volatile backing store? eg: are you using physical NV Modules, QEMU with '-device nvdimm', the GRUB 'mmap=<offset>!<size>', or something else?

I've run in to similar odd behaviour when using the GRUB method and Kernel Address Space Layout Randomisation (KASLR).  Admittedly this was on a smaller memory footprint.  At boot time, if the Kernel/BIOS allocates memory from a previously 'usable' region used for persistent memory, any overlapping regions/namespaces will be disabled and ndctl is unable to enable them.  Disabled namespaces results in the /dev/[dax|pmem] device(s) being unavailable which leads to 'failed to reconfigure namespace: No such device'.  

You can verify if you're running in to this scenario using this blog - [How To choose the correct Kernel parameter for pmem on your system](https://nvdimm.wiki.kernel.org/how_to_choose_the_correct_memmap_kernel_parameter_for_pmem_on_your_system).

Check your dmesg or 'journalctl -b' and look for 'persistent' and 'pmem' to see if errors were produced at boot time.

HTH

**Comment by stellarhopper** [comment]
@insanecoderr sounds like this could've been fixed with the recent alignment fixes. Feel free to reopen this if you are still seeing this problem.
