### ISSUE TITLE
ndctl_bus_cmd_new_ars_status returns 65476

### ISSUE THREAD

**Issue by FYBTT** [pmem/ndctl#46]
https://github.com/pmem/ndctl/blob/cf7086a432042c9cfb9ac75528fb836cffb79aea/test/daxdev-errors.c#L152
sorry, this is a question.
what's the 65476 means?

**Comment by stellarhopper** [comment]
Ah this test may need to be fixed. rc is not from ndctl_bus_cmd_new_ars_status, but from ndctl_cmd_submit. A positive return value for that indicates a buffer underrun, and in the case of ars_status, that is fine, since we can't expect the entire max_ars_out sized buffer to get filled.

I believe the test should've been checking for `if (rc < 0)`

**Comment by FYBTT** [comment]
thank you for your reply.
It looks fine after applied the resolution.
I have a one more question.When I inject an error in a real AEP device with cscript
```
>>?aep.set_poison_bit(enable=1, men_mode=4, DPA=0x90000000)
>>?aep.set_address_range_scrub(enable=1, start_DPA=0x90000000, end_DPA=0x90000100)
>>?aep.get_long_operation_status()
-------------------------------
*    Long Operation Status    *
-------------------------------
Command : Set Features (05h) / Address Range Scrub (04h)
Percent Complete : 100%
Estimated Time to Completion (ETC) :  0s
Status Code : Success (Command was successfully completed)
The number of errors found during the range scrub : 1
Max DPA Error Addresses Reached : Normal
DPA Error Addresses [ 0] : 0x90000000
```
so， what should the params of `ndctl_bus_cmd_new_ars_cap(bus, start, size)` be？

**Comment by stellarhopper** [comment]
libndctl doesn't know about DIMM addresses, it only operates from a system physical address point of view. The DIMM address to physical address translation depends on how the interleave set is set up etc.  The addresses expected by the ARS APIs are system physical addresses, and for a namespace, they can be obtained using the ndctl_{namespace,pfn,dax}_get_resource APIs

**Comment by FYBTT** [comment]
Thanks. actually, I have tried using ndctl_region_get_resource API to get the start SPA of persistent memory. Let the address equal 'base'.
PS：System have only one region
```shell
-------------------------------
*    Long Operation Status    *
-------------------------------
Command : Set Features (05h) / Address Range Scrub (04h)
Percent Complete : 100%
Estimated Time to Completion (ETC) :  0s
Status Code : Success (Command was successfully completed)
The number of errors found during the range scrub : 1
Max DPA Error Addresses Reached : Normal
DPA Error Addresses [ 0] : 0x90000000
```
0x90000000(16)->2415919104(10)
Does 2415919104 means offset？
 I tried ndctl_bus_cmd_new_ars_cap(bus, base+2415919104, N) , but ndctl_cmd_ars_num_records API always returns 0.
replace N with ndctl_region_get_size(region), replace 2415919104 with 0, ndctl_cmd_ars_num_records returns 0 as well. what's more it finished in 2 seconds.
Why the API always return 0？
Could you give me some suggesttions？thx

**Comment by stellarhopper** [comment]
The DPA is the DIMM relative address, and is different from the System Physical Address. Only one region can still mean you have multiple DIMMs interleaved. So you'd need to figure out what the namespace (or region) offset is going to be for that DPA, and then add that to the address obtained from _get_resource.

As for ndctl_cmd_ars_num_records returning zero, there was a bug we fixed recently: https://patchwork.kernel.org/patch/10444419/

This hasn't appeared in a release yet, but I can push it to the pending branch and you can retest with that.

**Comment by FYBTT** [comment]
I git clone the tag V60.3 and patch the [https://patchwork.kernel.org/patch/10444419/]( https://patchwork.kernel.org/patch/10444419/).
actually, System has only one region and only one namespace.
I tried repalcing ndctl_region_get_resource with ndctl_namespace_get_resource, but get the same
base.
I tried ndctl inject-error as well.
 ```shell
>>ndctl list
{
  "dev":"namespace2.0",
  "mode":"devdax",
  "size":264239054848,
  "uuid":"289bfa35-ffb3-49f0-8004-528f334e10da",
  "raw_uuid":"52401ec5-b0b8-4d38-8a12-179487c94e6f",
  "chardev":"dax2.0",
  "numa_node":0,
  "badblock_count":14
}



>>ndctl inject-error --block=258045952 --count=8 namespace2.0
{
  "dev":"namespace2.0",
  "mode":"devdax",
  "size":264239054848,
  "uuid":"289bfa35-ffb3-49f0-8004-528f334e10da",
  "raw_uuid":"52401ec5-b0b8-4d38-8a12-179487c94e6f",
  "chardev":"dax2.0",
  "numa_node":0,
  "badblock_count":22,
  "badblocks":[
    {
      "offset":1,
      "length":1,
      "dimms":[
        "nmem0"
      ]
    },
    {
      "offset":11,
      "length":3,
      "dimms":[
        "nmem2"
      ]
    },
    {
      "offset":15,
      "length":7,
      "dimms":[
        "nmem0",
        "nmem2"
      ]
    },
    {
      "offset":24,
      "length":3,
      "dimms":[
        "nmem2"
      ]
    },
    {
      "offset":258045952,
      "length":8,
      "dimms":[
        "nmem0"
      ]
    }
  ]

```
so I can get base with ndctl_namespace_get_resource
than I call ndctl_bus_cmd_new_ars_cap(bus, base+258045952\*512, 8\*512) , but ndctl_cmd_ars_num_records API returns 0

**Comment by FYBTT** [comment]
@stellarhopper 
when I get the region offset with `ndctl list -RM`
```
{
  "dev":"region2",
  "size":268435456000,
  "available_size":0,
  "type":"pmem",
  "numa_node":0,
  "iset_id":6650375655470404176,
  "badblock_count":14,
  "badblocks":[
    {
      "offset":8196097,
      "length":1,
      "dimms":[
        "nmem0"
      ]
    },
    {
      "offset":8196107,
      "length":3,
      "dimms":[
        "nmem2"
      ]
    },
    {
      "offset":8196111,
      "length":7,
      "dimms":[
        "nmem0",
        "nmem2"
      ]
    },
    {
      "offset":8196120,
      "length":3,
      "dimms":[
        "nmem2"
      ]
    }
  ],
  "persistence_domain":"unknown"
}
```
and get base with ndctl_region_get_resource API, 
ndctl_bus_cmd_new_ars_cap(bus, base+8196120*512, 30*512)
finaly I get err_records:
```
err records num:28
check_ars_query: record[0].addr: 0x217a203000
check_ars_query: record[0].length: 0x100
check_ars_query: record[1].addr: 0x217a203100
check_ars_query: record[1].length: 0x100
check_ars_query: record[2].addr: 0x217a203200
check_ars_query: record[2].length: 0x100
check_ars_query: record[3].addr: 0x217a203300
check_ars_query: record[3].length: 0x100
check_ars_query: record[4].addr: 0x217a203400
check_ars_query: record[4].length: 0x100
check_ars_query: record[5].addr: 0x217a203500
check_ars_query: record[5].length: 0x100
check_ars_query: record[6].addr: 0x217a203600
check_ars_query: record[6].length: 0x100
check_ars_query: record[7].addr: 0x217a203700
check_ars_query: record[7].length: 0x100
check_ars_query: record[8].addr: 0x217a203800
check_ars_query: record[8].length: 0x100
check_ars_query: record[9].addr: 0x217a203900
check_ars_query: record[9].length: 0x100
check_ars_query: record[10].addr: 0x217a203a00
check_ars_query: record[10].length: 0x100
check_ars_query: record[11].addr: 0x217a203b00
check_ars_query: record[11].length: 0x100
check_ars_query: record[12].addr: 0x217a203c00
check_ars_query: record[12].length: 0x100
check_ars_query: record[13].addr: 0x217a203d00
check_ars_query: record[13].length: 0x100
check_ars_query: record[14].addr: 0x217a204000
check_ars_query: record[14].length: 0x100
check_ars_query: record[15].addr: 0x217a204100
check_ars_query: record[15].length: 0x100
check_ars_query: record[16].addr: 0x217a204200
check_ars_query: record[16].length: 0x100
check_ars_query: record[17].addr: 0x217a204300
check_ars_query: record[17].length: 0x100
check_ars_query: record[18].addr: 0x217a204400
check_ars_query: record[18].length: 0x100
check_ars_query: record[19].addr: 0x217a204500
check_ars_query: record[19].length: 0x100
check_ars_query: record[20].addr: 0x217a204600
check_ars_query: record[20].length: 0x100
check_ars_query: record[21].addr: 0x217a204700
check_ars_query: record[21].length: 0x100
check_ars_query: record[22].addr: 0x217a204800
check_ars_query: record[22].length: 0x100
check_ars_query: record[23].addr: 0x217a204900
check_ars_query: record[23].length: 0x100
check_ars_query: record[24].addr: 0x217a204a00
check_ars_query: record[24].length: 0x100
check_ars_query: record[25].addr: 0x217a204b00
check_ars_query: record[25].length: 0x100
check_ars_query: record[26].addr: 0x217a204c00
check_ars_query: record[26].length: 0x100
check_ars_query: record[27].addr: 0x217a204d00
check_ars_query: record[27].length: 0x100
```
Amazing, but why it returns 28 errors start at "offset":8196120 ?
THX

**Comment by stellarhopper** [comment]
@FYBTT That sounds right, as you have a total of 14 badblocks, which are 512B each. The error records show a length of 0x100 which is 256B, and hence 28 records.

**Comment by djbw** [comment]
@FYBTT this issue has gone off topic. If you identify another problem with the implementation we can address it, but we're otherwise not here to debug your usage of the API. @stellarhopper fixed the reported bug here: https://patchwork.kernel.org/patch/10444419/

The general recommendation for ARS is to let the kernel handle it.

**Comment by insanecoderr** [comment]
which version has patched this one: https://patchwork.kernel.org/patch/10444419/?
