### ISSUE TITLE
configure failed on ubuntu

### ISSUE THREAD

**Issue by yaelna** [pmem/ndctl#47]
when running ./configure CFLAGS='-g -O2' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64 I get the following error:
...
configure: creating ./config.status
config.status: error: cannot find input file: `Documentation/daxctl/Makefile.in'

[autogen-out.txt](https://github.com/pmem/ndctl/files/2072776/autogen-out.txt)
[configure-out.txt](https://github.com/pmem/ndctl/files/2072777/configure-out.txt)

**Comment by djbw** [comment]
We'll take a look, but in the meantime you can use the prebuilt package from the Canonical Server Team:

https://launchpad.net/~canonical-server/+archive/ubuntu/nvdimm/

...this will eventually be added to Ubuntu as a standard package.

**Comment by stellarhopper** [comment]
@yaelna Documentation/daxctl/Makefile.in should've been created when you run autogen.sh. Can you start with a clean repo, and run that, and verify whether Documentation/daxctl/Makefile.in is missing?
If it is, can you try ./autogen.sh --force

**Comment by stellarhopper** [comment]
I'm not able to reproduce this in an ubuntu environment. Please reopen if this is still a problem.
