### ISSUE TITLE
Can ctrl-c be destructive to ndctl reconfiguration?

### ISSUE THREAD

**Issue by jchu314atgithub** [pmem/ndctl#48]
I have an 'fsdax' mode namespace, start to reconfigure it to 'raw' mode,  then quickly followed by a few ctrl-c's to interrupt the process.   Consequently the namespace became 'disabled', and cannot be re-enabled. 
Question: can ctrl-c be destructive to the namespace? if yes, why?  if no, how to recover?
thanks!

**Comment by djbw** [comment]
Reconfiguring is always a destructive operation in that all metadata on the namespace is wiped and then the new configuration is applied. You might need to explicitly re-destroy the namespace before trying to apply the new configuration with:

    ndctl destroy-namespace namespaceX.Y

**Comment by jchu314atgithub** [comment]
Sounds good, thanks!
