### ISSUE TITLE
fail to get the error info via ARS API

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#49]
the version of ndctl:60.3+ with patch(https://patchwork.kernel.org/patch/10444419/)

I tried to get the ARS result of a specified range after i successfully submitted the ars start cmd,however the ndctl_cmd_ars_in_progress() API is always returning non-zero which means the ARS is in progress

the ARS length is 2560bytes which is reasonable.so is the ARS start address.

Below is some related info:

**1.err info:**
[root@localhost fV3]# ndctl list -RM
{
  "dev":"region1",
  "size":134217728000,
  "available_size":0,
  "type":"pmem",
  "numa_node":2,
  "iset_id":3168996772246421800,
  "badblock_count":1,
  "badblocks":[
    {
      "offset":4194306,
      "length":1,
      "dimms":[
        "nmem0"
      ]
    }
  ],
  "persistence_domain":"unknown"
}

**2.BIOS log during the ARS procedure:**
(DSM) DsmServeNgnCommandsFromOS BEGIN: function 1, input len 16
[CR] (DSM) DsmQueryArsCapabilities: range <0x30C0000400:0x30C0001800)
[CR] (ARS) GetScrubbableInterleaveSets: Getting interleave sets from: 0x30C0000400 - 0x30C00017FF
[CR] (ARS) GetScrubbableInterleaveSets: BaseAddress = 0x3040000000, Limit = 0x4F80000000 - PMEM
[CR] (ARS) GetScrubbableInterleaveSets: 1 PMEM interleave sets found
[CR] (DSM) DsmQueryArsCapabilities: returning Success (interface status 0x20000)
[CR] (DSM) DsmServeNgnCommandsFromOS END: status 0x20000, output len 12
[CR] (DSM) DsmServeNgnCommandsFromOS BEGIN: function 2, input len 24
[CR] (DSM) DsmStartArs: range <0x30C0000400:0x30C0001800), type: 0x0002, flags: 0x00
[CR] (ARS) GetScrubbableInterleaveSets: Getting interleave sets from: 0x30C0000400 - 0x30C00017FF
[CR] (ARS) GetScrubbableInterleaveSets: BaseAddress = 0x3040000000, Limit = 0x4F80000000 - PMEM
[CR] (ARS) GetScrubbableInterleaveSets: 1 PMEM interleave sets found
[CR] (DSM) DsmServeNgnCommandsFromOS END: status 0x6, output len 4
[CR] (DSM) DsmServeNgnCommandsFromOS BEGIN: function 3, input len 0
[CR] (DSM) DsmQueryArsStatus ()
[CR] (ARS) DsmGetArsStatus ()
[CR] (DSM) DsmServeNgnCommandsFromOS END: status 0x10000, output len 44

**Comment by djbw** [comment]
Are you resubmitting the ARS status command? It needs to resubmitted in a loop.

**Comment by djbw** [comment]
It looks like the the libndctl routines are operating correctly. I can only offer libndctl answers through this page you would need to talk to your platform vendor for BIOS support for DSM behavior. Otherwise, BIOS behavior questions are out of scope for this issues page.
