### ISSUE TITLE
Got "fatal: Not a git repository (or any of the parent directories): .git" when copiling ndctl-53.1.tar.gz

### ISSUE THREAD

**Issue by yide1728** [pmem/ndctl#5]
Pls check below steps:
wget https://github.com/pmem/ndctl/archive/v53.1.tar.gz#/ndctl-53.1.tar.gz
tar xvf ndctl-53.1.tar.gz
cd ndctl-53.1
./autogen.sh 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

----------------------------------------------------------------
Initialized build system. For a common configuration please run:
----------------------------------------------------------------

./configure CFLAGS='-g -O0' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64

**Comment by djbw** [comment]
These messages are benign, but I will send a fix to clean them up.

Thanks for the report!
