### ISSUE TITLE
ndctl list -RM cannot show the badblocks

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#54]
the version of ndctl:60.3+

As i inject an error using cscript( a tool provided by intel),the ndctl list -RM command cannot show the badblocks afterwards. It seems like random case,I used to find it work well.

Notes:After I do read instruction in OS,CPU will triggere MCE as expected.Then, ndctl list -RM can show the badblock info.

**Comment by djbw** [comment]
Only after ARS or directly consuming poison will the kernel know about media errors. This is behaving as expected.

**Comment by insanecoderr** [comment]
Thanks for your reply.
But it fails to show the badblocks  after ARS(ndctl start-scrub;ndctl wait-scrub).
In dmesg,it records:"nift ACPI0012:00: range 1 ars timeout,aborting"...it seems like ARS fails..
