### ISSUE TITLE
ars timeout 

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#55]
ndctl it fails to show the badblocks after ARS(ndctl start-scrub;ndctl wait-scrub).
In dmesg,it records:"nift ACPI0012:00: range 1 ars timeout,aborting"...it seems like ARS fails..

**Comment by djbw** [comment]
Known problem, fixed in the v4.17 kernel. See commit bc6ba8085842 "nfit, address-range-scrub: rework and simplify ARS state machine".
