### ISSUE TITLE
what is the relationship between region and SPA?

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#56]
Question:
Given a SPA,can I get the regionID?

**Comment by djbw** [comment]
Well, not directly. You could iterate all regions with ndctl_region_foreach() and then interrogate ndctl_region_get_resource() which is the SPA base.

**Comment by insanecoderr** [comment]
Then,How do i get all the region names?

**Comment by djbw** [comment]
??

You can enumerate all regions like this:

ndctl_bus_foreach(ctx, bus)
    ndctl_region_foreach(bus, region)
        ndctl_region_get_resource(region);
