### ISSUE TITLE
man page commands in Header & Footer are truncated

### ISSUE THREAD

**Issue by sscargal** [pmem/ndctl#58]
I've noticed the man page for commands that are longer than 20 characters, including the section (1), are being truncated in the header and footer.  

`# ndctl --version
61.4.g08a96c6
`
`# uname -r
4.17.2-200.fc28.x86_64
`

For example:

```
# man ndctl-enable-region
NDCTL-ENABLE-REGIO(1)	ndctl Manual	NDCTL-ENABLE-REGIO(1)
[...]
ndctl 61.4.g08a96c6	06/29/2018	NDCTL-ENABLE-REGIO(1)
```

```
# man ndctl-enable-namespace
NDCTL-ENABLE-NAMES(1)	ndctl Manual	NDCTL-ENABLE-NAMES(1)
[...]
ndctl 61.4.g08a96c6	06/29/2018	NDCTL-ENABLE-NAMES(1)
```

The expectation is to see the complete command in the header/footer to avoid confusion.

**Comment by stellarhopper** [comment]
Hm, never noticed this until now, but interestingly, building with asciidoctor instead of asciidoc (--enable-asciidoctor to 'configure') doesn't truncate like this.

Maybe it is time to switch the default..

**Comment by djbw** [comment]
Cool, we can at least change the default in the rpm specfile as a first step.

**Comment by djbw** [comment]
We have switched the default to asciidoctor, please re-open if you still see issues.
