### ISSUE TITLE
ndctl doesn't show the size for btt namespaces

### ISSUE THREAD

**Issue by ljkhpe** [pmem/ndctl#6]
As reported in email:

My system has 4 8G NVDIMMs and I have them configured in different ways, as you can
see from the ndctl output:

$ ndctl list
[
  {
    "dev":"namespace3.0",
    "mode":"raw",
    "size":8589934592,
    "blockdev":"pmem3"
  },
  {
    "dev":"namespace2.0",
    "mode":"memory",
    "size":8587837440,
    "uuid":"2567d762-68ae-486b-a6eb-2d3ab1b9dca9",
    "blockdev":"pmem2"
  },
  {
    "dev":"namespace1.0",
    "mode":"sector",
    "uuid":"44fb474e-7db8-4438-ad95-05ecb9f2075e",
    "sector_size":4096,
    "blockdev":"pmem1s"
  },
  {
    "dev":"namespace0.0",
    "mode":"memory",
    "size":8453619712,
    "uuid":"933ed54b-5b64-47f1-8409-c88f7c846522",
    "blockdev":"pmem0"
  }
]

The two memory namespaces have different sizes because one is --map=dev and the other is --map=mem.
It would be nice if the map option was displayed but my question is about the size value for the
btt device, or lack of one.

All the namespaces show a size except for the btt.  The btt only shows a sector size.  There
is no size value exposed by the btt sysfs information, which is probably why it's not in ndctl.
Vishal now has a patch in flight to expose the size for btt devices.

**Comment by djbw** [comment]
Fixed as of the kernel-4.8-rc2 and ndctl-54:

# ndctl list --namespace=namespace0.0 
{
  "dev":"namespace0.0",
  "mode":"sector",
  "size":8580472832,
  "uuid":"f675d270-2bf7-424a-ab7b-2536295f3215",
  "sector_size":4096,
  "blockdev":"pmem0s"
}
