### ISSUE TITLE
fix init-labels operation count

### ISSUE THREAD

**Issue by djbw** [pmem/ndctl#60]
```
# ndctl init-labels all
nmem5: regions active, abort label write
nmem4: regions active, abort label write
nmem3: regions active, abort label write
nmem2: regions active, abort label write
nmem1: regions active, abort label write
nmem0: regions active, abort label write
initialized 1016 nmems
```

**Comment by sscargal** [comment]
Can we fix the `initialized 1016 nmems` message.  Only 6 nmems were affected, not 1016.  This should say `initialized 1016 labels` or `initialized 1016 labels on 6 nmems`?  Since there are usually 510 labels per nmem I see why this issue was created.

**Comment by stellarhopper** [comment]
A fix for this is now in 'pending' and will be in v66
