### ISSUE TITLE
Who triggers ARS on every boot?

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#61]
I found that screen print about ARS on every boot when loading OS. 

Who triggers the ARS?

I believe its not BIOS,because when I turn off the "Start ARS on boot" option in UEFI the print still exists.

Here is the screen print:
[CR] (DSM) DsmServeNgnCommandsFromOS BEGIN: function 2, input len 24
[CR] (DSM) DsmStartArs: range <0x3040000000:0x4F80000000), type: 0x0002, flags: 0x02
[CR] (ARS) GetScrubbableInterleaveSets: Getting interleave sets from: 0x3040000000 - 0x4F7FFFFFFF
[CR] (ARS) GetScrubbableInterleaveSets: BaseAddress = 0x3040000000, Limit = 0x4F80000000 - PMEM
[CR] (ARS) GetScrubbableInterleaveSets: 1 PMEM interleave sets found
[CR] (ARS) GetScrubbableInterleaveSets: Getting interleave sets from: 0x3040000000 - 0x4F7FFFFFFF
[CR] (ARS) GetScrubbableInterleaveSets: BaseAddress = 0x3040000000, Limit = 0x4F80000000 - PMEM
[CR] (ARS) GetScrubbableInterleaveSets: 1 PMEM interleave sets found
[CR] (ARS) 4 scrubber records, filter start: 0x3040000000, filter end: 0x4F7FFFFFFF
[CR] (ARS) 4 errors total
[CR] (ARS) DsmGetArsStatus ()
[CR] (DSM) DsmServeNgnCommandsFromOS END: status 0x0, output len 4
[CR] (DSM) DsmServeNgnCommandsFromOS BEGIN: function 3, input len 0
[CR] (DSM) DsmQueryArsStatus ()
[CR] (ARS) DsmGetArsStatus ()
[CR] (DSM) DsmServeNgnCommandsFromOS END: status 0x0, output len 140

**Comment by davejiang** [comment]
The OS will check to see if BIOS has launched ARS, and if there are regions not covered, the OS will launch ARS. It is recommended to disable ARS launching from BIOS and allow the OS to manage that. Starting with 4.17 the OS will issue the quick ARS to detect the bad areas already marked by the BIOS. The nfit kernel module has a module parameter "no_init_ars" to skip ARS run at init.
