### ISSUE TITLE
[check-labels] prints 'nmems' instead of 'labels' in the report

### ISSUE THREAD

**Issue by sscargal** [pmem/ndctl#63]
**Config**

OS: Fedora 28
Kernel: 4.17.9-200.fc28.x86_64
ndctl version: 61.5.g77fa917

**Issue**

When checking labels, the report prints 'nmems' instead of 'labels'

```
# ndctl check-labels nmem2
successfully verified 510 nmems
```

There aren't 510 nmem devices on my system, but there are 510 label slots per index on nmem2

```
$ ndctl check-labels nmem2 | jq '{dev, index}'
{
  "dev": "nmem2",
  "index": [
    {
      "signature": "NAMESPACE_INDEX",
      "major": 1,
      "minor": 2,
      "labelsize": 256,
      "seq": 3,
      "nslot": 510
    },
    {
      "signature": "NAMESPACE_INDEX",
      "major": 1,
      "minor": 2,
      "labelsize": 256,
      "seq": 2,
      "nslot": 510
    }
  ]
}
```

**Expected Output**

I would expect to see something similar to the following showing how many labels were read.

```
# ndctl check-labels nmem2
successfully verified 510 labels on 1 nmem(s)
```

**Comment by stellarhopper** [comment]
v66 changes this to:

`successfully verified 1 nmem label`

Which doesn't leak the detail about the number of label slots to the user, and only talks about the number of DIMMs checked.
