### ISSUE TITLE
Namespace reconfigure fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by ykorman** [pmem/ndctl#7]
I've compiled ndctl (latest) for Ubuntu 16.04 and tried to run it in a qemu-kvm virtual machine configured with virtual nvdimms like so:
`root@vm:~/ndctl# ./ndctl/ndctl create-namespace --reconfig=namespace0.0 --mode=memory --map=mem --force --verbose`
And got the following result:
```
setup_namespace:322: pfn0.0: set_align failed: -6
failed to reconfigure namespace
libndctl: ndctl_unref: context 0x19e2340 released
```
The original pmem device goes away after that.

Ubuntu is based on kernel 4.4, maybe it's missing some features required by the latest ndctl.

**Comment by djbw** [comment]
Yes, that's a bug.  We should be skipping attempts to set the alignment an older kernels that did not include this capability.  I'll copy you on the proposed fix.

**Comment by djbw** [comment]
These 2 patches fix the issue for me:

https://patchwork.kernel.org/patch/9420495/
https://patchwork.kernel.org/patch/9420497/

If they work for you I'll push them out on the pending branch.

**Comment by ykorman** [comment]
They work for me as well.
Thanks!

**Comment by djbw** [comment]
Thanks, pushed out to the pending branch.
