### ISSUE TITLE
make check : fail

### ISSUE THREAD

**Issue by dranandrao** [pmem/ndctl#70]
I have installed all the dependencies required for ndctl.

BuildRequires:	autoconf
BuildRequires:	asciidoc
BuildRequires:	xmlto
BuildRequires:	automake
BuildRequires:	libtool
BuildRequires:	pkgconfig
BuildRequires:	pkgconfig(libkmod)
BuildRequires:	pkgconfig(libudev)
BuildRequires:	pkgconfig(uuid)
BuildRequires:	pkgconfig(json-c)
BuildRequires:	pkgconfig(bash-completion)
BuildRequires: systemd

But make check is failing.
[make_check_output.txt](https://github.com/pmem/ndctl/files/2441246/make_check_output.txt)

Please help me get through.

**Comment by djbw** [comment]
Yes, sorry, known issue. Please give the 'pending' branch a try. It has this fix:

011fc692270b ndctl, test: add UUID_LIBS for list_smart_dimm

**Comment by panlinux** [comment]
Also reported in https://github.com/pmem/ndctl/issues/66 :)

**Comment by dranandrao** [comment]
I tried with every branch(57, pending) but faced the same issue.
Fixed it using CFLAGS -luuid -lkmod.

**Comment by djbw** [comment]
@dranandrao can you send the output of make check when running on the pending branch? You shouldn't need to specify that to CFLAGS.

**Comment by stellarhopper** [comment]
Closing as #66 was closed in v63. Please reopen/create a new issue if there is still a build failure.
