### ISSUE TITLE
ndctl61.2,can not find nvdimm

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#71]
the nvdimm is intel optane DC Pmem(512G version).

in UEFI shell, the tool provided by intel can find the nvdimm in heathy state. However,in OS,"ndctl list -D" can not show any information.

Moreover,the ipmctl tool which is provided by INTEL shows that the dimm is non-functional which may be a wrong interpretation since the dimm is actually functional as the UEFI tool shows.

**Comment by djbw** [comment]
What does "ndctl list -Di" show?

The DIMMs might be disabled due to a failure to read labels, I do not believe the UEFI driver takes this detail into account.

**Comment by stellarhopper** [comment]
Closing since this is unrelated to ndctl.
