### ISSUE TITLE
Bogus error reported destroying AppDirectNotInterleaved namespaces

### ISSUE THREAD

**Issue by swdavenport** [pmem/ndctl#73]
With ndctl v63, there is a bogus error message and code reported when destroying AppDirectNonInterleaved type namespaces:

[root@ban ~]# ipmctl show -region

SocketID             ISetID    PersistentMemoryType  Capacity FreeCapacity HealthState
       0 0xedfbda90d31b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy
       0 0x63f1da90121a8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy
       0 0x0a05da90891c8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy
       0 0xb3fbda901a1b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy
       1 0x0ffbda90f01b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy
       1 0x73fbda90fa1b8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy
       1 0xea05da90b91c8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy
       1 0x3df1da905b1a8a22 AppDirectNotInterleaved 125.0 GiB    125.0 GiB     Healthy

[root@ban ~]# ndctl create-namespace --region=region1 -s 96G
[root@ban ~]# ndctl create-namespace --region=region3 -s 64G
[root@ban ~]# ndctl create-namespace --region=region5 -s 32G
[root@ban ~]# ndctl list -N | grep -A1 namespace 
    "dev":"namespace1.0",
    "mode":"fsdax",
...
    "dev":"namespace3.0",
    "mode":"fsdax",
...
    "dev":"namespace5.0",
    "mode":"fsdax",

[root@ban ~]# ndctl destroy-namespace -f all
error destroying namespaces: No such device or address
destroyed 3 namespaces
[root@ban ~]# echo $?                                       
250

The error does *not* happen with AppDirect namespace types.

**Comment by stellarhopper** [comment]
@swdavenport I'm curious to see what namespace caused the error.
Other than the three namespaces you created above, were there any other namespaces on the system?
You can do, prior to creating the three namespaces above:

```ndctl list -iBDRN```

In case there are other namespaces listed, how does destroy-namespace all behave before creating any namespaces?

One thing that could be getting hit was fixed recently: https://patchwork.kernel.org/patch/10595261/
I've pushed that to the pending branch - would you also mind giving that a try and see if the problem still exists?

**Comment by swdavenport** [comment]
@stellarhopper Yes... looking into gathering the data.

**Comment by swdavenport** [comment]
@stellarhopper , info below

> @swdavenport I'm curious to see what namespace caused the error.
Other than the three namespaces you created above, were there any other namespaces on the system?

There are none.  namespace(s) cleanup/removal ahead to the testing.  In another word, there will be no active namespace at that instant.

# ndctl list -iBDRN | egrep -A4  "namespace[0-9]" | egrep "namespace|state"
            "dev":"namespace1.0",
            "state":"disabled"
            "dev":"namespace1.1",
            "state":"disabled"
            "dev":"namespace3.1",
            "state":"disabled"
            "dev":"namespace3.0",
            "state":"disabled"
            "dev":"namespace5.1",
            "state":"disabled"
            "dev":"namespace5.0",
            "state":"disabled"
            "dev":"namespace7.0",
            "state":"disabled"
            "dev":"namespace7.1",
            "state":"disabled"
            "dev":"namespace0.1",
            "state":"disabled"
            "dev":"namespace0.0",
            "state":"disabled"
            "dev":"namespace2.1",
            "state":"disabled"
            "dev":"namespace2.0",
            "state":"disabled"
            "dev":"namespace4.0",
            "state":"disabled"
            "dev":"namespace4.1",
            "state":"disabled"
            "dev":"namespace6.1",
            "state":"disabled"
            "dev":"namespace6.0",
            "state":"disabled"

# ndctl destroy-namespace -f all
error destroying namespaces: No such device or address
destroyed 0 namespaces
# echo $?
250

# ndctl list -iBDRN
[
  {
    "provider":"ACPI.NFIT",
    "dev":"ndbus0",
    "scrub_state":"idle",
    "dimms":[
      {
        "dev":"nmem1",
        "id":"8089-a2-1751-000004c9",
        "handle":17,
        "phys_id":67
      },
      {
        "dev":"nmem3",
        "id":"8089-a2-1751-0000049d",
        "handle":273,
        "phys_id":80
      },
      {
        "dev":"nmem5",
        "id":"8089-a2-1751-000004a9",
        "handle":4113,
        "phys_id":93
      },
      {
        "dev":"nmem7",
        "id":"8089-a2-1751-00000482",
        "handle":4369,
        "phys_id":106
      },
      {
        "dev":"nmem0",
        "id":"8089-a2-1751-00000538",
        "handle":1,
        "phys_id":63
      },
      {
        "dev":"nmem2",
        "id":"8089-a2-1751-00000487",
        "handle":257,
        "phys_id":76
      },
      {
        "dev":"nmem4",
        "id":"8089-a2-1751-000003c1",
        "handle":4097,
        "phys_id":89
      },
      {
        "dev":"nmem6",
        "id":"8089-a2-1751-0000049f",
        "handle":4353,
        "phys_id":102
      }
    ],
    "regions":[
      {
        "dev":"region1",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":-5477544209317918174,
        "mappings":[
          {
            "dimm":"nmem1",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace1.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace1.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      },
      {
        "dev":"region3",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":-289397435030336990,
        "mappings":[
          {
            "dimm":"nmem3",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace3.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace3.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      },
      {
        "dev":"region5",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":8357513849722341922,
        "mappings":[
          {
            "dimm":"nmem5",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace5.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace5.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      },
      {
        "dev":"region7",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":-1298203752014312926,
        "mappings":[
          {
            "dimm":"nmem7",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace7.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace7.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      },
      {
        "dev":"region0",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":722223629573327394,
        "mappings":[
          {
            "dimm":"nmem0",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace0.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace0.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      },
      {
        "dev":"region2",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":2304675949965969954,
        "mappings":[
          {
            "dimm":"nmem2",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace2.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace2.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      },
      {
        "dev":"region4",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":7201777591456008738,
        "mappings":[
          {
            "dimm":"nmem4",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace4.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace4.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      },
      {
        "dev":"region6",
        "size":134217728000,
        "available_size":134217728000,
        "type":"pmem",
        "iset_id":1151754445761776162,
        "mappings":[
          {
            "dimm":"nmem6",
            "offset":268435456,
            "length":134217728000,
            "position":0
          }
        ],
        "persistence_domain":"memory_controller",
        "namespaces":[
          {
            "dev":"namespace6.1",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          },
          {
            "dev":"namespace6.0",
            "mode":"raw",
            "size":0,
            "uuid":"00000000-0000-0000-0000-000000000000",
            "state":"disabled"
          }
        ]
      }
    ]
  }
]

> In case there are other namespaces listed, how does destroy-namespace all behave before creating any namespaces?

don't believe the issue is in the three namespaces that were created in corresponding region[1,3,5]. So, here is another example of creating just one namespace in region2 - which is also represent the scenario as questioned:
# ndctl list -N
# ndctl create-namespace --region=region2
{
  "dev":"namespace2.0",
  "mode":"fsdax",
  "map":"dev",
  "size":"123.04 GiB (132.12 GB)",
  "uuid":"413723a2-9965-4063-b8f2-7d3f6da0413d",
  "raw_uuid":"574d9651-4008-40c1-99a0-bd280cee88a8",
  "sector_size":512,
  "blockdev":"pmem2",
  "numa_node":0
}

# ndctl list -N
[
  {
    "dev":"namespace2.0",
    "mode":"fsdax",
    "map":"dev",
    "size":132118478848,
    "uuid":"413723a2-9965-4063-b8f2-7d3f6da0413d",
    "blockdev":"pmem2"
  }
]
#  ndctl destroy-namespace -f all
error destroying namespaces: No such device or address
destroyed 1 namespace
# echo $?
250

**Comment by swdavenport** [comment]
The pending branch was also tried. Same problem. :(

**Comment by stellarhopper** [comment]
@swdavenport I just posted a patch that should fix this:
https://patchwork.kernel.org/patch/10752943/

I've also updated the pending branch.

I'd be happy to add a Reported-by tag for you if I can get a name/email.

**Comment by swdavenport** [comment]
@stellarhopper Yup! That worked. Looking forward to the next release.

[root@b ~]# ndctl destroy-namespace -f all
error destroying namespaces: No such device or address
destroyed 3 namespaces

with pending gate
[root@b ndctl-63+]# ndctl destroy-namespace -f all
destroyed 7 namespaces

Note also it appears the original bug might only repro if you have an odd number of namespaces.
