### ISSUE TITLE
Could you provide the make uninstall command support?

### ISSUE THREAD

**Issue by MagicVin** [pmem/ndctl#77]
How to remove the older if I want to install the newer ndctl tool.

**Comment by djbw** [comment]
The "uninstall" make target works for me, what problem are you seeing? Otherwise the expectation is to use a binary ndctl from your Linux distribution provider.

**Comment by MagicVin** [comment]
Ok, It's my fault that didn't see the uninstall rule in the Makefile.
The "make uninstall" command works, Thank you very much.
