### ISSUE TITLE
Fix the security.sh ndctl reference 

### ISSUE THREAD

**Issue by Sriharshayd** [pmem/ndctl#82]
Pls fix the recent added the security.sh ndctl reference 

File : https://github.com/pmem/ndctl/blob/master/test/security.sh
Issue : 
++ ndctl list -b nfit_test.0 -d nmem1 -i
./security.sh: line 66: ndctl: command not found
++ jq -r '.[].dimms[0].handle'

All the other reference to ndctl is done using : ../ndctl/ndctl  except in one place.

Proposed fix: 
--- security.sh.org	2019-02-11 19:47:25.654352202 -0800
+++ security.sh	2019-02-11 20:25:10.293352202 -0800
@@ -63,7 +63,7 @@ lock_dimm()
 	# inline. Once a subsequent user arrives we can refactor this to a
 	# helper in test/common:
 	#   get_test_dimm_path "nfit_test.0" "nmem3"
-	handle="$(ndctl list -b "$NFIT_TEST_BUS0"  -d "$dev" -i | jq -r .[].dimms[0].handle)"
+	handle="$($NDCTL list -b "$NFIT_TEST_BUS0"  -d "$dev" -i | jq -r .[].dimms[0].handle)"
 	test_dimm_path=""
 	for test_dimm in /sys/devices/platform/"$NFIT_TEST_BUS0"/nfit_test_dimm/test_dimm*; do
 		td_handle_file="$test_dimm/handle"

**Comment by stellarhopper** [comment]
@Sriharshayd Thanks for the report. I'll send a patch to fix this. If you would like me to add a Reported-by tag for you, please provide the name/email I can use.

**Comment by Sriharshayd** [comment]
You can use : Sriharsha Y D : sriharsha.devdas@oracle.com

**Comment by stellarhopper** [comment]
Fixed by fcb9f4a971295b442a1df6d30b1cc2a096b09b58
