### ISSUE TITLE
copy monitor.conf if not found for ndctl monitor 

### ISSUE THREAD

**Issue by Sriharshayd** [pmem/ndctl#83]
The current test framework fails to  copy monitor.conf to the default /etc/ndctl location resulting in 
" ndctl monitor" command failures during monitor tests.

File : https://github.com/pmem/ndctl/blob/master/test/monitor.sh
Failure: 
```
+ ../ndctl/ndctl monitor -l /tmp/tmp.cyyDKTRAPm -d nmem0
+ sleep 3
config-file: /etc/ndctl/monitor.conf cannot be opened
```

Observation : 
"ndctl monitor" looks for default config in /etc/ndctl/ location i.e /etc/ndctl/monitor.conf
Since the test framework doesnt copy this config file to /etc/ndctl location , notcied test failures.

Suggested patch : 
1. Copy the monitor.conf file if not found under /etc/ndctl/ & also needs to create this location if not found. ``
-----------------------------------------------------------
```
--- monitor.sh_org	2019-02-13 02:00:13.988373052 -0800
+++ monitor.sh	2019-02-13 02:00:22.178741021 -0800
@@ -14,6 +14,11 @@ smart_supported_bus=""
 
 . ./common
 
+if [ ! -f "/etc/ndctl/monitor.conf" ];then 
+   [ ! -d  "/etc/ndctl" ] && mkdir -p /etc/ndctl
+   cp ../ndctl/monitor.conf /etc/ndctl/monitor.conf
+fi 
+
 trap 'err $LINENO' ERR
 check_min_kver "4.15" || do_skip "kernel $KVER may not support monitor service"
```
----------------------------------------------------------
though not using the " -c, --config-file= " option for ndctl monitor as this option is already covered in this testcase [monitor.sh: test_conf_file () ]

**Comment by stellarhopper** [comment]
Hm, I don't know if copying a new /etc/ndctl/monitor.conf blindly is the right solution - we don't want a test wiping out global system config (even though it is unlikely that the test will be run in a production environment, it applies for developers' environments too).

I wonder if the real fix is to not /require/ the config file to be present in /etc
If the required options are fully specified on the command line, that should:
a. override anything in /etc , and
b. not require the /etc config to be present

i.e. we should only complain about missing config when neither of -c, /etc/ or command line options completely specify the monitor parameters.

Indeed I can run "touch /etc/ndctl/monitor.conf; ndctl monitor;", with the config being blank, and that works fine - so enforcing the presence of the file seems unnecessary.

@djbw thoughts?
@QIFuli care to send a fix for this? (or I'm curious to hear if you have any other thoughts maybe around why this was chosen).

Thanks,
-Vishal

**Comment by Sriharshayd** [comment]
>>I don't know if copying a new /etc/ndctl/monitor.conf blindly is the right solution - we don't want a test >>wiping out global system config 
Agree over here ,  to account for this  the below piece of code is suggested in the fix,i.e  to check for the existence of  config file before copying ,
if [ ! -f "/etc/ndctl/monitor.conf" ];then

**Comment by stellarhopper** [comment]
> Agree over here , to account for this the below piece of code is suggested in the fix,i.e to check for the existence of config file before copying
> if [ ! -f "/etc/ndctl/monitor.conf" ];then

True - though I'd still prefer to look into removing the requirement entirely first.

**Comment by QIFuli** [comment]
Sorry for missing out this issue.
I think it will make sense to remove the requirement of default configuration file.
I will try to make a patch to fix it.

**Comment by stellarhopper** [comment]
Thanks Qi!

**Comment by stellarhopper** [comment]
@Sriharshayd The above commit (now in the pending branch) should fix the problem, and I'll close this. Feel free to reopen if it is still a problem.
