### ISSUE TITLE
How to enable a locked dimm after a reboot.

### ISSUE THREAD

**Issue by etsaur4** [pmem/ndctl#85]
How do you unlock/enable a dimm when "keyctl show -x" no longer has the encrypted nvdimm key?
FYI: I'm pretty ignorant about keyctl and how it works.

Using the test/security.sh as an example.

setup_keys()
setup_passphrase()
...reboot...  <== once this happens all the keys in keyctl disappears.

How do you add the encrypted nvdimm key back to key ring?

# ndctl enable-dimm nmem0
libndctl: ndctl_dimm_enable: nmem0: failed to enable
enabled 0 nmem

debug message in DMESG
[  670.793436] nvdimm_bus_probe: nd_bus ndbus0: START: nvdimm.probe(nmem0)
[  670.793925] nvdimm_request_key: nvdimm nmem0: request_key() found no key
[  670.793926] nvdimm_probe: nvdimm nmem0: failed to unlock dimm: -126
[  670.794306] systemd-journald[1195]: no db file to read /run/udev/data/+nd:ndbus0: No such file or directory
[  670.796703] nd_label_data_init: nvdimm nmem0: failed to init config data area: (65152:131072)
[  670.796704] nvdimm_drvdata_release: nvdimm nmem0: trace
[  670.796706] nvdimm_bus_probe: nd_bus ndbus0: END: nvdimm.probe(nmem0) = -6
[  670.797226] systemd-journald[1195]: no db file to read /run/udev/data/+nd:ndbus0: No such file or directory

**Comment by djbw** [comment]
The expectation is that "ndctl load-keys" is triggered at init-time and pre-populates the key-ring before the driver loads. See /etc/modprobe.d/nvdimm-security.conf that's installed by ndctl.

**Comment by etsaur4** [comment]
ah.. I see.. this explains why my test worked the first time.   I waited a bit.  For a few minutes no keys shows up and ndctl load-keys doesn't do anything obvious.

The keys also look like they get unloaded or expired.

The key doesn't get loaded.  Even when I manage to get the key to load, enabling doesn't work.

# keyctl show -x
Session Keyring
0x3cd08a6c --alswrv      0     0  keyring: _ses
0x0f0d172c --alswrv      0 65534   \_ keyring: _uid.0
0x2c9549a4 --alswrv      0     0   \_ encrypted: nvdimm:8089-a2-1839-00000538
7913758: key inaccessible (Key has expired)

# ndctl enable-dimm nmem1
libndctl: ndctl_dimm_enable: nmem1: failed to enable
enabled 0 nmem

# ndctl list -D
  {
    "dev":"nmem1",
    "id":"8089-a2-1839-00000538",
    "handle":17,
    "phys_id":67,
    "state":"disabled",
    "security":"locked"
  },

There is a blob in /etc/ndctl/keys for the dimm.

Is there a way to "keyctl padd user" a new key with the same passphrase and associate it with a nvdimm?

**Comment by davejiang** [comment]
What master key did you use to create the encrypted key for the nvdimm? That master key has to stay in the key ring for the encrypted key to be valid. You can certainly load the encrypted key again if the master key is available. For example:
keyctl add encrypted nvdimm:cdab-0a-07e0-ffffffff "load `cat nvdimm.cdab-0a-07e0-ffffffff.blob`" @u

**Comment by etsaur4** [comment]
For "masterkey" are you referring to keyctl padd command?  Like 'keyctl padd user "$masterkey"'.  

For the below examples $masterkey = "nvdimm-key" in my tests

Basically I followed the steps in /test/security.sh.  Except instead of generating a random 32 byte, I used a simple password like "changeme".  Or do this line 'keyctl pipe "$(keyctl search @u user $masterkey)" > "$masterpath"'

I tried variants of the command you mentioned and that never seemed to work.  After a reboot keyctl is basically empty...  Minutes later a encrypted nvdimm entry shows but my user:nvdimm-key entry never does.  Can I recreate my masterkey?

 # keyctl show -x
Session Keyring
0x3cd08a6c --alswrv      0     0  keyring: _ses
0x0f0d172c --alswrv      0 65534   \_ keyring: _uid.0

 # keyctl add encrypted nvdimm:8089-a2-1835-00001a21 "load `cat nvdimm_8089-a2-1839-00000538_ban25uut138.us.test.com.blob`" @u
add_key: Required key not available

 # echo "changeme" | keyctl padd user "nvdimm-key" @u     
797016358

 # keyctl add encrypted nvdimm:8089-a2-1835-00001a21 "load `cat nvdimm_8089-a2-1839-00000538_ban25uut138.us.oracle.com.blob`" @u
[ 7999.461308] encrypted_key: key user:nvdimm-key not found
[ 8186.153207] encrypted_key: bad hmac (-22)
add_key: Invalid argument

 # keyctl show -x
Session Keyring
0x3cd08a6c --alswrv      0     0  keyring: _ses
0x0f0d172c --alswrv      0 65534   \_ keyring: _uid.0
0x2f818126 --alswrv      0     0       \_ user: nvdimm-key

**Comment by davejiang** [comment]
Ok so basically you are using a user key just like the test instead of a trusted-key via the TPM. So you need to load your master key before the nvdimm key. After you created the master user-key, you'll need to create a key blob for it so you can load it later. You can do:
keyctl pipe <master_key_id> > nvdimm-master.blob
Basically your encrypted keys can't be used unless the master key is loaded properly. 

Right now the load-key command expects the master key to be named nvdimm-master.blob. We may need a better way to support multiple master keys.

**Comment by davejiang** [comment]
https://wiki.gentoo.org/wiki/Extended_Verification_Module#Setting_up_EVM
This web page is pretty helpful with showing how the key stuff works.

**Comment by etsaur4** [comment]
Thanks.. I got much further.  The nvdimm-master.blob part I think did the trick..  Thanks for the links, I'll read them first.

**Comment by etsaur4** [comment]
Hi David, 

2 questions
- Load-keys has never worked for me.  Is there a secret?
- If you loose the blob files in /etc/ndctl/keys is there a way to recover and recreate the encrypted nvdimm key?

**Comment by davejiang** [comment]
On Mar 25, 2019, 5:08 PM -0700, etsaur4 <notifications@github.com>, wrote:
> Hi David,
> 2 questions
> Load-keys has never worked for me. Is
> there a secret?

The master key blob has to be named nvdimm-master.blob. You did create a master key blob?
> If you loose the blob files in /etc/ndctl/keys is there a way to recover and recreate the encrypted nvdimm key?
>
No. That's why in the man pages it says you are responsible for backing them up. The encrypted payloads are randomly generated by the kernel.

**Comment by djbw** [comment]
> No. That's why in the man pages it says you are responsible for backing them up. The encrypted payloads are randomly generated by the kernel.

That said, secure erase leaves the DIMMs in the unlocked state if you need to re-provision the passphrase.

**Comment by etsaur4** [comment]
Thanks Dan, that info leads to an interesting segway.

There is a test were we ran passphrase_setup/secure erase in a loop using ndctl 64.  The loop suddenly failed at one point and all the blobs disappeared.  No dmesg or warning that I could find.  I suspect ndctl thought secure erase succeeded and erased the blobs.  This was one of the fears we had when ndctl required the dimm to enable security before doing a secure erase.

The above could also be a user problem, but as I understand it the loop ran fine for a while.

**Comment by davejiang** [comment]
I recently posted patches to allow secure erase without security enabled
via the -z switch to pass in a zero key. It requires kernel and ndctl
updates though.

**Comment by etsaur4** [comment]
Thanks, I've been following that.  I am surprise a kernel update is needed.

**Comment by djbw** [comment]
Yes, it's a change in direction for where we headed previously. It turns out that the "zero-key" semantic was already implemented for master-passphrase and overwrite, so for completeness the "zero-key" capability is being made common across all security commands. With that in place it makes more sense to support platforms that might allow "passphrase-less" security operations with the zero-key facility. This is a fix that is suitable for 5.1-rc and 5.0-stable.

**Comment by davejiang** [comment]
So I found the bug in load-keys for user master keys. Will post fix.

**Comment by etsaur4** [comment]
Looks all good, closing
