### ISSUE TITLE
[Docs] Typo in Documentation/ndctl/intel-nvdimm-security.txt

### ISSUE THREAD

**Issue by sscargal** [pmem/ndctl#86]
In [Documentation/ndctl/intel-nvdimm-security.txt](https://github.com/pmem/ndctl/blob/master/Documentation/ndctl/intel-nvdimm-security.txt) there's a typo on Line 94

`
Remove the enrypted passphrase from the kernel's user keyring.
`

should be

`
Remove the encrypted passphrase from the kernel's user keyring.
`

Fix: change 'enrypted' to 'encrypted'

**Comment by stellarhopper** [comment]
PR applied manually: e1fc1bf1e452269f7e973763f2f639efdaa2c180
