### ISSUE TITLE
[Doc] 'disable-passphrase' should be 'remove-passphrase'

### ISSUE THREAD

**Issue by sscargal** [pmem/ndctl#87]
The [CRYPTO (SECURE) ERASE](https://github.com/pmem/ndctl/blob/master/Documentation/ndctl/intel-nvdimm-security.txt) documentation currently makes reference to a non-existent command 'disable-passphrase' which was replaced by 'remove-passphrase'.  Lines 107-109:

`
=== CRYPTO (SECURE) ERASE

This operation is similar to disable-passphrase. 
`

Should say

`
=== CRYPTO (SECURE) ERASE

This operation is similar to remove-passphrase. 
`

**Comment by stellarhopper** [comment]
PR applied manually: a8a1d7dd5d9b0525131cba05d644f3c970be360f
