### ISSUE TITLE
some questions about pmdk

### ISSUE THREAD

**Issue by insanecoderr** [pmem/ndctl#90]
Since I can not create issues in pmdk project,I have to issue my question about pmdk here.
Could you tell me how to call PMDK functions/interfaces using python? 
Thanks. If you can't help,do you know who to turn to？

**Comment by andyrudoff** [comment]
Hi,

We have a separate repo for PMDK issues: https://github.com/pmem/issues/issues

To answer your question, we have an experimental repo with python bindings to libpmemobj, but it is definitely not ready for any serious use and hasn't had attention for a while: https://github.com/pmem/pynvm

Hope that helps.
