### ISSUE TITLE
numa node info is not visible(release v64.1)

### ISSUE THREAD

**Issue by LuyaoZhong** [pmem/ndctl#93]
When I use the latest code, I can't see the numa node info when creating namespace and listing namespaces. Our team and I are doing some work based on the ndctl , the numa node info is very import for us, although we can get numa node info by v61.2, we still want to use the latest ndctl code. 

$ ndctl list  -X # v64.1
[
  {
    "dev":"namespace0.2",
    "mode":"devdax",
    "map":"mem",
    "size":4292870144,
    "uuid":"72444757-c5f0-4c40-b5d1-c3a1055b3eed",
    "chardev":"dax0.2",
    "align":2097152
  },
  {
    "dev":"namespace0.0",
    "mode":"devdax",
    "map":"mem",
    "size":17177772032,
    "uuid":"264c8309-514d-4660-b602-5a1fb7a03bbd",
    "chardev":"dax0.0",
    "align":2097152,
    "name":"pmem_namespace_region0_2"
  }
]

$ ndctl list -X # v61.2
[
  {
    "dev":"namespace0.2",
    "mode":"devdax",
    "map":"mem",
    "size":4292870144,
    "uuid":"72444757-c5f0-4c40-b5d1-c3a1055b3eed",
    "raw_uuid":"9e0d2051-7e9d-4d98-a99f-9c72bbf1dde9",
    "daxregion":{
      "id":0,
      "size":4292870144,
      "align":2097152,
      "devices":[
        {
          "chardev":"dax0.2",
          "size":4292870144
        }
      ]
    },
    "numa_node":0
  },
  {
    "dev":"namespace0.0",
    "mode":"devdax",
    "map":"mem",
    "size":17177772032,
    "uuid":"264c8309-514d-4660-b602-5a1fb7a03bbd",
    "raw_uuid":"d9ee9f5c-1985-4ba7-bbc7-e6d75cf534d3",
    "daxregion":{
      "id":0,
      "size":17177772032,
      "align":2097152,
      "devices":[
        {
          "chardev":"dax0.0",
          "size":17177772032
        }
      ]
    },
    "name":"pmem_namespace_region0_2",
    "numa_node":0
  }
]

**Comment by djbw** [comment]
numa_node and a few other properties have moved to be output under the "verbose" option:

    ndctl list -v

Does that work for your use case?

**Comment by stellarhopper** [comment]
Please reopen if this is still a problem
