### ISSUE TITLE
ndctl list should return a JSON array even when there is only one namespace

### ISSUE THREAD

**Issue by LuyaoZhong** [pmem/ndctl#94]
'ndctl list' will return a JSON array if there are more than one namespaces
$ ndctl list
[
  {
    "dev":"namespace1.0",
    "mode":"raw",
    "size":268435456000,
    "sector_size":512,
    "blockdev":"pmem1",
    "numa_node":1
  },
  {
    "dev":"namespace0.0",
    "mode":"devdax",
    "map":"mem",
    "size":4292870144,
    "uuid":"a0509e82-15c5-4d4f-8a1f-06271ecd45fd",
    "raw_uuid":"dfd4080c-a1ab-4e6e-923d-128051a393a6",
    "chardev":"dax0.0",
    "numa_node":0
  }
]

but it will return a JSON object if there is only one namespace
$ ndctl list
{
  "dev":"namespace1.0",
  "mode":"raw",
  "size":268435456000,
  "sector_size":512,
  "blockdev":"pmem1",
  "numa_node":1
}

I think JSON array will be better and more reasonable, just like this :
$ ndctl list
[
{
  "dev":"namespace1.0",
  "mode":"raw",
  "size":268435456000,
  "sector_size":512,
  "blockdev":"pmem1",
  "numa_node":1
}
]

**Comment by djbw** [comment]
What version? This behavior has been fixed since ndctl v62 with commit:

72c46ab194d9 ndctl list: always output array without --human

**Comment by LuyaoZhong** [comment]
Both master and v61.2 have this issue.

**Comment by stellarhopper** [comment]
Please reopen if this is still an issue
