### ISSUE TITLE
AEP: How to Identify Namespace region associate with CPU

### ISSUE THREAD

**Issue by Muthu2112** [pmem/ndctl#97]
After creating namespace I need to identify which CPU being associated with namespace from ndctl command. Similar to "IPMCTL show -region" command shows Socket ID

Is there way ?

**Comment by sscargal** [comment]
@Muthu2112 , yes.  Use the `ndctl list -Nv` to show verbose output for namespaces.  This will report the `numa_node`.  For example:

```
# ndctl list -Nv
[
  {
    "dev":"namespace1.0",
    "mode":"fsdax",
    "map":"mem",
    "size":1623495540736,
    "uuid":"835774ee-ae7b-456a-bdb1-f71ec377d4c0",
    "raw_uuid":"a3f14176-a2a1-4a2a-89bf-0ba2c089fcde",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem1",
    "numa_node":1
  },
  {
    "dev":"namespace0.0",
    "mode":"fsdax",
    "map":"mem",
    "size":1623495540736,
    "uuid":"9293107f-2a0d-4362-a631-e50dbd37a666",
    "raw_uuid":"2b19335b-3222-42b9-ab28-272b6a5fd247",
    "sector_size":512,
    "align":2097152,
    "blockdev":"pmem0",
    "numa_node":0
  }
]
```

FYI, you can also ask questions on the [Persistent Memory Google Group](https://groups.google.com/forum/#!forum/pmem).
